# Citrics Documentation - Data Collection

The data used in the project was from a number of different sources. Merging data from these data sources required making a uniform naming convention for each city, the data science team decided to use a format of `city_name ST`, where 'ST' is the postal abbreviation used for each state. The combined data set exceeds the file size that we can add to github, so that csv file isn't availabe, but could be pulled from our MongoDB.

The most comprehensive data set that we built off of was the US Census Data (https://www.census.gov/acs/www/data/data-tables-and-tools/data-profiles/2018/).

## Census Data
#### Census Data Collection Methodology

The process for collecting the Census data was fairly manual. We went to the Census Website:  https://data.census.gov/cedsci/table?q=&d=ACS%205-Year%20Estimates%20Data%20Profiles&table=DP02&tid=ACSDP5Y2017.DP02&lastDisplayedRow=39&hidePreview=true&g=0100000US.160000 and performed the following steps

1) Select the Geographies option from the navigation bar

2) Clear anything in the "Selected Geographies:" across the bottom of the page

3) From the remaining Geography column, scroll and select "Place", a "Place" column will appear

4) Scroll and select which state you need the data for, that state's name will appear in a new column
- Note: for some of the Tables you will be able to select multiple states at a time to speed up this process

5) From that column, select the first option "all places in state_name"

<img src = 'https://raw.githubusercontent.com/Lambda-School-Labs/city-data-comparison-ds/master/images/census-select-geographies.PNG'>
6) Hit the close button in the bottom right corner

7) Select "Download Table"

8) Select that you want the file as a csv with the date you want

- NOTE: The population of each city from 2010 through the most recently available year, came from the above process as well, but at step 8 select an earlier year.

9) You'll then have a zip file with the data for that state/time

10) Repeat 1-9 until you have all states for that particular table

11) Then from the top-left corner of the page, select the "Tables" link

<img src = 'https://raw.githubusercontent.com/Lambda-School-Labs/city-data-comparison-ds/master/images/census-tables-highlighted.PNG'>
12) Select another table (in total, you'll need DP02, DP03, DP04, and DP05) 

13) Select "Customize Table" from the top-right corner of the page and repeat steps 1-12 until you've collected the entirety of the data needed

#### Feature Selection

We also went through a manual process of looking at the 2000+ columns in this combined data set. At the DS Team's discretion, we selected the following features:

In [5]:
import pandas as pd

In [6]:
cenesus_column_headers = pd.read_csv('https://raw.githubusercontent.com/Lambda-School-Labs/city-data-comparison-ds/master/data-help/census-columns.csv')

In [10]:
print(cenesus_column_headers.shape)
cenesus_column_headers.head()

(381, 1)

  column_headers
0     DP02_0001E
1     DP02_0002E
2    DP02_0002PE
3    DP02_0004PE
4     DP02_0017E

#### Merging

The `GEO_ID` field was used as the key to merge assorted Census DataFrames on.

## Walk Score Data Collection Methodology

Walk Score is a service that offers a uniform scoring methodology to rate cities overall as well as specific addresses on their walkability, how bike-friendly they are, and a score for the public transit available. Using a third party for this because we do not have to make our own methodology for these types of figures.

About Walk Score:
https://www.walkscore.com/professional/research.php

Source of the data tables:
https://www.walkscore.com/cities-and-neighborhoods/states/

Trademark Guidelines:
https://www.walkscore.com/trademark-use.shtml

In [1]:
import pandas as pd

In [33]:
us_state_abbrev = ['AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN','IA','KS',
                   'KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC',
                   'ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY']

In [37]:
# Empty DataFrame to add to in the loop below
df = pd.DataFrame()

for i in us_state_abbrev:
    df_i = pd.read_html('https://www.walkscore.com/' + i)[0]
    df_i['State'] = i
    df = pd.concat([df, df_i])

This is a simple loop that uses the `pd.read_html` function and a list of state abbreviations to scrape the summary scores for all major cities in their publicly-available data tables.

In [39]:
df.head()

,City,Zip Code,Walk Score,Transit Score,Bike Score,Population,State
0,Birmingham (the largest city in Alabama),35211.0,35,25,31,212237,AL
1,Montgomery,36109.0,27,16,38,205764,AL
2,Mobile,36605.0,33,--,39,195111,AL
3,Huntsville,35810.0,23,13,40,180105,AL
4,Tuscaloosa,NaN,33,--,37,90468,AL

### Real Estate Data Collection Methodology - Zillow

The process for collecting Zillow's real estate data was similar to that of the Census data, go to their website: https://www.zillow.com/research/data/ and perform the following steps:

**Home Values**

1) Housing data is collected from the the top option on this page, we collected five "Data Types" from the drop down (`ZHVI 1-Bedroom Time Series ($)`, `ZHVI 2-Bedroom Time Series ($)`, through 5-Bedroom+)

2) And for Geography select "City"

3) Download, this gives you a csv file

4) Repeat steps 1-3 for each Data Type

### Latitude - Longitude Data Source

For the majority of lat-long locations, we got a csv file from: https://simplemaps.com/data/us-cities

For those cities not listed we used the Mapbox API: https://docs.mapbox.com/api/

In [ ]:
def get_data(url):
    """
    Where url is a city name.
    
    Going through nested arrays:
        - state ID
        - city name - entire "Place" value from the census data
        - GEOID
    """
    
    get = requests.get(f"https://api.mapbox.com/geocoding/v5/mapbox.places/{url[1]}.json?types=place&country=US&access_token=GET-YOUR-OWN-DANG-TOKEN").json()
    try:
        check_first = get['features'][0]['context'][0]['short_code'].split('-')[1] #checking that the city is in the right state
        if check_first == url[0]:
            locs = get['features'][0]['center']
            lat = locs[1]
            lng = locs[0]
            place = get['features'][0]['place_name']
        else:
            lat = True
            lng = True
            place = True
    except:
        lat = False
        lng = False
        place = False
    res = [url[0], url[1], url[2], lat, lng, place]
    return(res)

### Weather Data Collection Methodology

Source for the weather data: https://www.ncdc.noaa.gov/cdo-web/webservices/v2#gettingStarted

Using the latitude/longitude data collected above, we used a function in NOAA's api called 'extent' which effectively draws a bounding box around a location and returns all weather stations in that area, sort by data coverage and you have a weather station ID to use to pull other data from.

In [ ]:
def stations(i):
    lat = dataset['lat'].iloc[i]
    lng = dataset['lng'].iloc[i]
    
    # Using one half a degree in each direction from each city (~35 miles)
    def box_size(lng):
        if lng < -170: # Island chain off of Alaska
            return 7
        elif lng > -125: #Basically all of the lower 48
            return 1
        else:
            return 2.5 # The rest of Alaska
        
    coord_len = box_size(lng)
        
    
    N_coord = lat + coord_len
    S_coord = lat - coord_len
    W_coord = lng - coord_len
    E_coord = lng + coord_len
    
    # Note that for this particular API the coordinates MUST be in this order: SWNE
    boundingbox = 'extent=' + str(S_coord) + ',' + str(W_coord) + ',' + str(N_coord) + ',' + str(E_coord)
    
    
    # Search stations within the 'boundingbox' defined above,
    # only for stations that record TEMP and SUN,
    # data must exist later than December 2018 for 'Global Summary of the Month', 
    # limited to 500 stations (shouldn't be a constraint, basically just saying show all)
    get_stations = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/stations?' + boundingbox + '&datacategoryid=TEMP&startdate=2019-12-01&datasetid=GSOM&limit=500',
                       headers={'token': 'GET-YOUR-OWN-DANG-TOKEN'})
    station_json = get_stations.json()
    try:
        station_data = station_json['results']
        df_station_data = pd.DataFrame(station_data)
        df_station_data = df_station_data.sort_values(by='datacoverage', ascending=0)
        search_station_0 = df_station_data['id'].iloc[0]
        return search_station_0
    except:
        pass


all_stations = []

t1 = time.perf_counter()
for i in range(1, 300): #I had to break the pull up into smaller chunks and run multiple times to get it to work.
    all_stations.append(stations(i))
t2 = time.perf_counter()
print(f'Finished in {t2-t1} seconds')

Drop the duplicates from the list of stations and return the station info for the exact lat/lng for which the data you'll pull is associated:

In [ ]:
df_locations = pd.DataFrame()

t1 = time.perf_counter()

for i in [0]:

    station_n = df_as2['station'][i]

    if station_n == None:
        pass
    else:
        get = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/stations/' + station_n,
                           headers={'token':'GET-YOUR-OWN-DANG-TOKEN'})

        locations_json = get.json()
        df = pd.DataFrame.from_dict(locations_json, orient='index').T
        
        df_locations = pd.concat([df_locations, df], axis=0)

    
t2 = time.perf_counter()
print(f'Finished in {t2-t1} seconds')

Now take the list of station IDs and get the actual weather data:

In [ ]:
df_locations = pd.DataFrame()

t1 = time.perf_counter()

for i in range(550, 684):

    station_n = df_locations_all['id'][i]

    if station_n == None:
        pass
    else:
        get = requests.get('https://www.ncdc.noaa.gov/cdo-web/api/v2/data?datasetid=GSOM&datatypeid=TAVG,TMAX,TMIN,PRCP,SNOW,PSUN&stationid=' + station_n + '&startdate=2016-01-01&enddate=2019-12-01&units=standard&limit=500',
                           headers={'token':'GET-YOUR-OWN-DANG-TOKEN'})

        weather_json = get.json()
        weather_data = weather_json['results']
        weather_df = pd.DataFrame(weather_data)

        df_pivot = weather_df.pivot(index='date', columns='datatype', values='value')

        headers=df_pivot.columns

        df_pivot['date'] = pd.to_datetime(df_pivot.index, infer_datetime_format=True)
        df_pivot['Month'] = df_pivot['date'].dt.month.astype(str)

        df_columns=['station', 'Month', 'PRCP-AVG', 'SNOW-AVG', 'TAVG-AVG', 'TMIN-AVG', 'TMAX-AVG']

        if('PRCP' in headers):
            df_pivot['PRCP-AVG'] = df_pivot.groupby(['Month'])['PRCP'].transform('mean')
        else:
            df_pivot['PRCP-AVG'] = np.nan

        if('SNOW' in headers):
            df_pivot['SNOW-AVG'] = df_pivot.groupby(['Month'])['SNOW'].transform('mean')
        else:
            df_pivot['SNOW-AVG'] = np.nan

        if('TAVG' in headers):
            df_pivot['TAVG-AVG'] = df_pivot.groupby(['Month'])['TAVG'].transform('mean')
        else:
            df_pivot['TAVG-AVG'] = np.nan

        if('TMAX' in headers):
            df_pivot['TMAX-AVG'] = df_pivot.groupby(['Month'])['TMAX'].transform('mean')
        else:
            df_pivot['TMAX-AVG'] = np.nan

        if('TMIN' in headers):
            df_pivot['TMIN-AVG'] = df_pivot.groupby(['Month'])['TMIN'].transform('mean')
        else:
            df_pivot['TMIN-AVG'] = np.nan

        df_pivot['station'] = station_n
        df_output = df_pivot[df_columns].copy()
        df_output = df_output.reset_index()
        df_output = df_output.drop('date', axis=1)
        df_output = df_output.drop_duplicates()
        df_output['Month'] = df_output['Month'].astype(int)
        df_output = df_output.sort_values(by='Month', ascending=1)
        df_output = df_output.set_index('Month')

        x = df_output.to_dict()  
        df = pd.DataFrame()

        df_output
        if len(df_output.index) == 12:
            df['station'] = [x['station'][1]]
        else:
            headers = []

        if('PRCP' in headers):
            df['PRCP-AVG-1'] = [x['PRCP-AVG'][1]]
            df['PRCP-AVG-2'] = [x['PRCP-AVG'][2]]
            df['PRCP-AVG-3'] = [x['PRCP-AVG'][3]]
            df['PRCP-AVG-4'] = [x['PRCP-AVG'][4]]
            df['PRCP-AVG-5'] = [x['PRCP-AVG'][5]]
            df['PRCP-AVG-6'] = [x['PRCP-AVG'][6]]
            df['PRCP-AVG-7'] = [x['PRCP-AVG'][7]]
            df['PRCP-AVG-8'] = [x['PRCP-AVG'][8]]
            df['PRCP-AVG-9'] = [x['PRCP-AVG'][9]]
            df['PRCP-AVG-10'] = [x['PRCP-AVG'][10]]
            df['PRCP-AVG-11'] = [x['PRCP-AVG'][11]]
            df['PRCP-AVG-12'] = [x['PRCP-AVG'][12]]
        else:
            df['PRCP-AVG-1'] = np.nan
            df['PRCP-AVG-2'] = np.nan
            df['PRCP-AVG-3'] = np.nan
            df['PRCP-AVG-4'] = np.nan
            df['PRCP-AVG-5'] = np.nan
            df['PRCP-AVG-6'] = np.nan
            df['PRCP-AVG-7'] = np.nan
            df['PRCP-AVG-8'] = np.nan
            df['PRCP-AVG-9'] = np.nan
            df['PRCP-AVG-10'] = np.nan
            df['PRCP-AVG-11'] = np.nan
            df['PRCP-AVG-12'] = np.nan


        if('SNOW' in headers):
            df['SNOW-AVG-1'] = [x['SNOW-AVG'][1]]
            df['SNOW-AVG-2'] = [x['SNOW-AVG'][2]]
            df['SNOW-AVG-3'] = [x['SNOW-AVG'][3]]
            df['SNOW-AVG-4'] = [x['SNOW-AVG'][4]]
            df['SNOW-AVG-5'] = [x['SNOW-AVG'][5]]
            df['SNOW-AVG-6'] = [x['SNOW-AVG'][6]]
            df['SNOW-AVG-7'] = [x['SNOW-AVG'][7]]
            df['SNOW-AVG-8'] = [x['SNOW-AVG'][8]]
            df['SNOW-AVG-9'] = [x['SNOW-AVG'][9]]
            df['SNOW-AVG-10'] = [x['SNOW-AVG'][10]]
            df['SNOW-AVG-11'] = [x['SNOW-AVG'][11]]
            df['SNOW-AVG-12'] = [x['SNOW-AVG'][12]]
        else:
            df['SNOW-AVG-1'] = np.nan
            df['SNOW-AVG-2'] = np.nan
            df['SNOW-AVG-3'] = np.nan
            df['SNOW-AVG-4'] = np.nan
            df['SNOW-AVG-5'] = np.nan
            df['SNOW-AVG-6'] = np.nan
            df['SNOW-AVG-7'] = np.nan
            df['SNOW-AVG-8'] = np.nan
            df['SNOW-AVG-9'] = np.nan
            df['SNOW-AVG-10'] = np.nan
            df['SNOW-AVG-11'] = np.nan
            df['SNOW-AVG-12'] = np.nan



        if('TAVG' in headers):
            df['TAVG-AVG-1'] = [x['TAVG-AVG'][1]]
            df['TAVG-AVG-2'] = [x['TAVG-AVG'][2]]
            df['TAVG-AVG-3'] = [x['TAVG-AVG'][3]]
            df['TAVG-AVG-4'] = [x['TAVG-AVG'][4]]
            df['TAVG-AVG-5'] = [x['TAVG-AVG'][5]]
            df['TAVG-AVG-6'] = [x['TAVG-AVG'][6]]
            df['TAVG-AVG-7'] = [x['TAVG-AVG'][7]]
            df['TAVG-AVG-8'] = [x['TAVG-AVG'][8]]
            df['TAVG-AVG-9'] = [x['TAVG-AVG'][9]]
            df['TAVG-AVG-10'] = [x['TAVG-AVG'][10]]
            df['TAVG-AVG-11'] = [x['TAVG-AVG'][11]]
            df['TAVG-AVG-12'] = [x['TAVG-AVG'][12]]
        else:
            df['TAVG-AVG-1'] = np.nan
            df['TAVG-AVG-2'] = np.nan
            df['TAVG-AVG-3'] = np.nan
            df['TAVG-AVG-4'] = np.nan
            df['TAVG-AVG-5'] = np.nan
            df['TAVG-AVG-6'] = np.nan
            df['TAVG-AVG-7'] = np.nan
            df['TAVG-AVG-8'] = np.nan
            df['TAVG-AVG-9'] = np.nan
            df['TAVG-AVG-10'] = np.nan
            df['TAVG-AVG-11'] = np.nan
            df['TAVG-AVG-12'] = np.nan


        if('TMAX' in headers):
            df['TMAX-AVG-1'] = [x['TMAX-AVG'][1]]
            df['TMAX-AVG-2'] = [x['TMAX-AVG'][2]]
            df['TMAX-AVG-3'] = [x['TMAX-AVG'][3]]
            df['TMAX-AVG-4'] = [x['TMAX-AVG'][4]]
            df['TMAX-AVG-5'] = [x['TMAX-AVG'][5]]
            df['TMAX-AVG-6'] = [x['TMAX-AVG'][6]]
            df['TMAX-AVG-7'] = [x['TMAX-AVG'][7]]
            df['TMAX-AVG-8'] = [x['TMAX-AVG'][8]]
            df['TMAX-AVG-9'] = [x['TMAX-AVG'][9]]
            df['TMAX-AVG-10'] = [x['TMAX-AVG'][10]]
            df['TMAX-AVG-11'] = [x['TMAX-AVG'][11]]
            df['TMAX-AVG-12'] = [x['TMAX-AVG'][12]]
        else:
            df['TMAX-AVG-1'] = np.nan
            df['TMAX-AVG-2'] = np.nan
            df['TMAX-AVG-3'] = np.nan
            df['TMAX-AVG-4'] = np.nan
            df['TMAX-AVG-5'] = np.nan
            df['TMAX-AVG-6'] = np.nan
            df['TMAX-AVG-7'] = np.nan
            df['TMAX-AVG-8'] = np.nan
            df['TMAX-AVG-9'] = np.nan
            df['TMAX-AVG-10'] = np.nan
            df['TMAX-AVG-11'] = np.nan
            df['TMAX-AVG-12'] = np.nan


        if('TMIN' in headers):
            df['TMIN-AVG-1'] = [x['TMIN-AVG'][1]]
            df['TMIN-AVG-2'] = [x['TMIN-AVG'][2]]
            df['TMIN-AVG-3'] = [x['TMIN-AVG'][3]]
            df['TMIN-AVG-4'] = [x['TMIN-AVG'][4]]
            df['TMIN-AVG-5'] = [x['TMIN-AVG'][5]]
            df['TMIN-AVG-6'] = [x['TMIN-AVG'][6]]
            df['TMIN-AVG-7'] = [x['TMIN-AVG'][7]]
            df['TMIN-AVG-8'] = [x['TMIN-AVG'][8]]
            df['TMIN-AVG-9'] = [x['TMIN-AVG'][9]]
            df['TMIN-AVG-10'] = [x['TMIN-AVG'][10]]
            df['TMIN-AVG-11'] = [x['TMIN-AVG'][11]]
            df['TMIN-AVG-12'] = [x['TMIN-AVG'][12]]
        else:
            df['TMIN-AVG-1'] = np.nan
            df['TMIN-AVG-2'] = np.nan
            df['TMIN-AVG-3'] = np.nan
            df['TMIN-AVG-4'] = np.nan
            df['TMIN-AVG-5'] = np.nan
            df['TMIN-AVG-6'] = np.nan
            df['TMIN-AVG-7'] = np.nan
            df['TMIN-AVG-8'] = np.nan
            df['TMIN-AVG-9'] = np.nan
            df['TMIN-AVG-10'] = np.nan
            df['TMIN-AVG-11'] = np.nan
            df['TMIN-AVG-12'] = np.nan

        df_locations = pd.concat([df_locations, df], axis=0)

    
t2 = time.perf_counter()
print(f'Finished in {t2-t1} seconds')

### API Endpoint for the front-end

The following is a link to the full documentation of the API to access the database the DS team assembled:
https://api.citrics.io/docs

Below is a series of code examples for accessing the endpoints.

In [1]:
import json
import requests

In [2]:
# An example of the city data being pulled by City ID
# Front-end has a dictionary with City Name, ID, Lat, Lng, and Population, with that they pass this endpoint the ID. 

city_example1 = requests.get('https://api.citrics.io/jkekal6d6e5si3i2ld66d4dl/citydata/17417')
city_example1 = city_example1.json()
city_example1

{'_id': 17417,
 'name_with_com': 'Fort Worth, TX',
 'city_no_st': 'Fort Worth',
 'census_full_name': 'Fort Worth city, Texas',
 'City': 'Fort Worth TX',
 'State': 'Texas',
 'st': 'TX',
 'geo_id': '1600000US4827000',
 'Latitude': 32.7812,
 'Longitude': -97.3472,
 'Total Population': 855786.0,
 'Population Male & Female': {'Male': 49.0, 'Female': 51.0},
 'Age Distribution': {'Under 5': 8.1,
  '5 to 9': 8.2,
  '10 to 14': 7.6,
  '15 to 19': 7.2,
  '20 to 24': 7.2,
  '25 to 34': 16.3,
  '35 to 44': 14.0,
  '45 to 54': 12.4,
  '55 to 59': 5.4,
  '60 to 64': 4.4,
  '65 to 74': 5.6,
  '75 to 84': 2.6,
  '85 years and over': 1.1},
 'Median Age': 32.2,
 'Population under 18': 28.3,
 'Population over 16': 74.7,
 'Ethnicity': {'White': 40.2,
  'Hispanic or Latino': 34.8,
  'African American': 18.4,
  'American Indian': 0.2,
  'Asian': 3.8,
  'Pacific Islander': 0.1,
  'other race': 0.2,
  'Two or more races': 2.3},
 'Marital Status': {'Males': {'Never Married': 37.2,
   'Currently Married': 48.1,
   'Separated': 2.2,
   'Divorced': 2.5},
  'Females': {'Never Married': 32.9,
   'Currently Married': 43.8,
   'Separated': 2.8,
   'Divorced': 6.4}},
 'Recent Mothers': {'Total': 14845.0,
  'Birth Rate': {'Avg': 67.0},
  'Age Distribution': {'15-19': 30.0, '20-34': 112.0, '35-50': 29.0},
  'National Avg': {'15-19': 17.29, '20-34': 103.95, '35-50': 19.82}},
 'School Enrollment': {'Preschool': 5.5,
  'Elementary': 43.7,
  'High school': 20.3,
  'College': 24.0},
 'Educational Attainment': {'Less than 9th grade': 9.1,
  '9th to 12th grade no diploma': 9.4,
  'High school': 24.8,
  'Some college no degree': 21.6,
  "Associate's degree": 6.7,
  "Bachelor's degree": 19.0,
  'Graduate degree': 9.3},
 'Language': {'English Only': 67.2,
  'Language other than English': 32.8,
  'Cannot Speak English': 14.0},
 'Two or more Languages': 18.799999999999997,
 'Unemployment Rate': 5.8,
 'Sex of Labor Force': {'Male': 39.8, 'Female': 60.2},
 'Commuting to Work': {'Drives Alone': 81.5,
  'Carpools': 11.4,
  'Public Transport': 0.9,
  'Walks': 1.3,
  'Works at home': 3.6,
  'Other transport': 1.3},
 'Mean Travel Time': 27.0,
 'Occupation': {'Management business science and arts occupations': 34.9,
  'Service occupations': 17.2,
  'Sales and office occupations': 23.7,
  'Natural resources construction and maintenance occupations': 10.3},
 'Industry': {'Agriculture forestry fishing and hunting and mining': 1.6,
  'Construction': 8.1,
  'Manufacturing': 11.0,
  'Wholesale trade': 3.2,
  'Retail trade': 10.7,
  'Transportation and warehousing and utilities': 7.4,
  'Information': 1.8,
  'Finance and insurance and real estate and rental and leasing': 7.1,
  'Professional scientific and management and administrative and waste management services': 10.4,
  'Educational services and health care and social assistance': 20.4,
  'Arts entertainment and recreation and accommodation and food services': 9.4,
  'Other services except public administration': 5.3,
  'Public administration': 3.8},
 'Class of Worker': {'Private wage and salary workers': 83.3,
  'Government workers': 11.0,
  'Self-employed in own not incorporated business workers': 5.6,
  'Unpaid family workers': 0.1},
 'Household Income': {'Less than USD 10,000': 7.1,
  'USD 10,000 - USD 14,999': 4.6,
  'USD 15,000 - USD 24,999': 9.2,
  'USD 25,000 - USD 34,999': 9.7,
  'USD 35,000 - USD 49,999': 12.7,
  'USD 50,000 - USD 74,999': 19.0,
  'USD 75,000 - USD 99,999': 13.2,
  'USD 100,000 - USD 149,999': 14.5,
  'USD 150,000 - USD 199,999': 5.2,
  'USD 200,000 or more': 4.7},
 'Median Household Income': 57309.0,
 'Mean Household Income': 76309.0,
 'Retirement Percent': {'With Social Security': 21.3,
  'With retirement income': 12.0,
  'With Supplemental Security Income': 5.3},
 'Retirement Avg': {'Mean Social Security income': 17444.0,
  'Mean retirement income': 24057.0,
  'Mean Supplemental Security Income': 9363.0},
 'Public Assistance Percent': {'With cash public assistance income': 1.5,
  'With Food Stamp/SNAP benefits': 14.7},
 'Median Per Capita Income': 31898.0,
 'Per Capita by Gender': {'Female': 39644.0, 'Male': 46647.0},
 'Health Insurance': 80.7,
 'Below Poverty Level': 13.0,
 'Total Housing Units': 312120.0,
 'Occupied Housing Units': {'Occupied Housing Units': 91.2,
  'Vacant Housing Units': 8.8},
 'Vacancy Rate': {'Homeowner vacancy rate': 1.2, 'Rental vacancy rate': 9.1},
 'Units in Structure': {'1-unit detached': 67.4,
  '1-unit attached': 3.3,
  '2 units': 1.7,
  '3 - 4 units': 3.1,
  '5 - 9 units': 5.5,
  '10 - 19 units': 7.9,
  '20 or more units': 9.6},
 'Total Housing units': 312120.0,
 'Year Built': {'2014 or later': 1.7,
  '2010 - 2013': 4.8,
  '2000 - 2009': 26.4,
  '1990 - 1999': 11.6,
  '1980 - 1989': 13.0,
  '1970 - 1979': 10.4,
  '1960 - 1969': 8.5,
  '1950 - 1959': 11.5,
  '1940 - 1949': 5.4,
  '1939 or earlier': 6.5},
 'Housing by rooms': {'1 room': 2.0,
  '2 rooms': 3.3,
  '3 rooms': 11.0,
  '4 rooms': 16.8,
  '5 rooms': 22.7,
  '6 rooms': 18.0,
  '7 rooms': 10.2,
  '8 rooms': 7.0,
  '9 rooms or more': 8.8},
 'Housing by bedrooms': {'No bedrooms': 2.2,
  '1 bedroom': 13.7,
  '2 bedrooms': 23.4,
  '3 bedrooms': 40.8,
  '4 bedrooms': 16.5,
  '5 bedrooms or more': 3.4},
 'Year Moved in': {'2015 or later': 14.2,
  '2010 - 2014': 38.6,
  '2000 - 2009': 29.1,
  '1990 - 1999': 9.3,
  '1980 - 1989': 3.8,
  '1979 and earlier': 4.9},
 'Occupants per room': {'1 or less': 94.7,
  '1 to one and a half ': 4.0,
  'one and a half or more': 1.2},
 'Vehicles Available': {'No vehicles available': 6.0,
  '1 vehicle available': 34.0,
  '2 vehicles available': 40.1,
  '3 or more vehicles available': 19.9},
 'Selected Monthly Owner Costs with Mortgage': {'Less than USD 500': 0.8,
  'USD 500 - USD 999': 15.4,
  'USD 1,000 - USD 1,499': 36.7,
  'USD 1,500 - USD 1,999': 27.6,
  'USD 2,000 - USD 2,499': 10.0,
  'USD 2,500 - USD 2,999': 4.7,
  'USD 3,000 or more': 4.8},
 'Median Selected Monthly Owner Costs with Mortgage': 1462.0,
 'Selected Monthly Owner Costs without Mortgage': {'Less than USD 250': 10.2,
  'USD 250 - USD 399': 21.5,
  'USD 400 - USD 599': 32.4,
  'USD 600 - USD 799': 17.9,
  'USD 800 - USD 999': 8.2,
  'USD 1,000 or more': 9.9},
 'Median Selected Monthly Owner Costs without Mortgage': 510.0,
 'Rent': {'Less than USD 500': 5.8,
  'USD 500 - USD 999': 48.0,
  'USD 1,000 - USD 1,499': 31.8,
  'USD 1,500 - USD 1,999': 10.7,
  'USD 2,000 - USD 2,499': 2.3,
  'USD 2,500 - USD 2,999': 0.9,
  'USD 3,000 or more': 0.5},
 'Median Rent': 967.0,
 'Population Growth': {'2010': 705349.0,
  '2011': 724699.0,
  '2012': 743865.0,
  '2013': 761092.0,
  '2014': 778573.0,
  '2015': 796614.0,
  '2016': 815930.0,
  '2017': 835129.0,
  '2018': 855786.0},
 'housing_helper': {'note': 'Property value data for Fort Worth TX provided by Zillow.',
  'no_zillow_city_data': False,
  'all_city_data_available': False,
  'all_bedroom_data_present': False,
  'includes_1bed': False,
  'includes_2bed': True,
  'includes_3bed': True,
  'includes_4bed': True,
  'includes_5bed': True,
  'includes_avgallhomes': True},
 'Historical Property Value Data': {'One Bedroom Houses': None,
  'Two Bedroom Houses': {'2008-01': 84421.0,
   '2008-02': 84178.0,
   '2008-03': 83875.3333333333,
   '2008-04': 83153.6666666667,
   '2008-05': 82285.0,
   '2008-06': 81844.0,
   '2008-07': 81601.3333333333,
   '2008-08': 81880.0,
   '2008-09': 81847.6666666667,
   '2008-10': 81692.0,
   '2008-11': 81511.3333333333,
   '2008-12': 81183.3333333333,
   '2009-01': 80767.3333333333,
   '2009-02': 80289.3333333333,
   '2009-03': 79973.0,
   '2009-04': 79802.3333333333,
   '2009-05': 79427.3333333333,
   '2009-06': 78867.0,
   '2009-07': 78353.6666666667,
   '2009-08': 77840.6666666667,
   '2009-09': 77383.6666666667,
   '2009-10': 77158.3333333333,
   '2009-11': 76964.3333333333,
   '2009-12': 77173.3333333333,
   '2010-01': 77053.3333333333,
   '2010-02': 76937.3333333333,
   '2010-03': 76563.3333333333,
   '2010-04': 76534.6666666667,
   '2010-05': 76550.6666666667,
   '2010-06': 76574.0,
   '2010-07': 76092.6666666667,
   '2010-08': 75547.0,
   '2010-09': 75011.6666666667,
   '2010-10': 74539.3333333333,
   '2010-11': 74140.0,
   '2010-12': 73433.0,
   '2011-01': 72911.0,
   '2011-02': 71863.0,
   '2011-03': 71243.3333333333,
   '2011-04': 70715.3333333333,
   '2011-05': 70436.0,
   '2011-06': 70034.3333333333,
   '2011-07': 69997.3333333333,
   '2011-08': 70245.0,
   '2011-09': 70653.0,
   '2011-10': 70611.3333333333,
   '2011-11': 70474.6666666667,
   '2011-12': 70171.3333333333,
   '2012-01': 69987.6666666667,
   '2012-02': 69478.0,
   '2012-03': 68951.6666666667,
   '2012-04': 68719.6666666667,
   '2012-05': 69123.6666666667,
   '2012-06': 69793.6666666667,
   '2012-07': 70191.0,
   '2012-08': 70227.6666666667,
   '2012-09': 69865.6666666667,
   '2012-10': 69609.6666666667,
   '2012-11': 69570.6666666667,
   '2012-12': 69792.0,
   '2013-01': 69685.3333333333,
   '2013-02': 69817.0,
   '2013-03': 69974.0,
   '2013-04': 70536.3333333333,
   '2013-05': 70919.3333333333,
   '2013-06': 71335.6666666667,
   '2013-07': 71951.6666666667,
   '2013-08': 72575.0,
   '2013-09': 73218.0,
   '2013-10': 73790.3333333333,
   '2013-11': 74228.0,
   '2013-12': 74801.6666666667,
   '2014-01': 74938.3333333333,
   '2014-02': 75082.3333333333,
   '2014-03': 75351.6666666667,
   '2014-04': 75834.3333333333,
   '2014-05': 76422.6666666667,
   '2014-06': 76840.6666666667,
   '2014-07': 77220.6666666667,
   '2014-08': 77557.0,
   '2014-09': 77752.3333333333,
   '2014-10': 78291.0,
   '2014-11': 79049.3333333333,
   '2014-12': 79757.3333333333,
   '2015-01': 80651.3333333333,
   '2015-02': 81488.0,
   '2015-03': 82374.0,
   '2015-04': 82853.3333333333,
   '2015-05': 83264.0,
   '2015-06': 83825.3333333333,
   '2015-07': 84345.3333333333,
   '2015-08': 85120.3333333333,
   '2015-09': 85675.6666666667,
   '2015-10': 86321.0,
   '2015-11': 86674.0,
   '2015-12': 87364.0,
   '2016-01': 88206.6666666667,
   '2016-02': 89513.6666666667,
   '2016-03': 90705.0,
   '2016-04': 91856.6666666667,
   '2016-05': 92750.3333333333,
   '2016-06': 93482.6666666667,
   '2016-07': 94158.3333333333,
   '2016-08': 94526.3333333333,
   '2016-09': 95191.0,
   '2016-10': 95851.3333333333,
   '2016-11': 96931.0,
   '2016-12': 98181.0,
   '2017-01': 99808.6666666667,
   '2017-02': 101625.66666666699,
   '2017-03': 103025.33333333301,
   '2017-04': 104256.33333333301,
   '2017-05': 105276.66666666699,
   '2017-06': 106590.0,
   '2017-07': 108024.0,
   '2017-08': 109366.0,
   '2017-09': 110744.66666666699,
   '2017-10': 112235.66666666699,
   '2017-11': 113751.66666666699,
   '2017-12': 114916.33333333301,
   '2018-01': 116244.33333333301,
   '2018-02': 117644.33333333301,
   '2018-03': 119393.33333333301,
   '2018-04': 120458.33333333301,
   '2018-05': 121247.66666666699,
   '2018-06': 121921.0,
   '2018-07': 122653.33333333301,
   '2018-08': 123073.0,
   '2018-09': 123769.0,
   '2018-10': 124704.0,
   '2018-11': 126304.66666666699,
   '2018-12': 128039.66666666699,
   '2019-01': 129926.33333333301,
   '2019-02': 131285.0,
   '2019-03': 132266.666666667,
   '2019-04': 132744.0,
   '2019-05': 133535.0,
   '2019-06': 133898.666666667,
   '2019-07': 134507.0,
   '2019-08': 135423.333333333,
   '2019-09': 137237.0,
   '2019-10': 138594.333333333,
   '2019-11': 138694.666666667},
  'Three Bedroom Houses': {'2008-01': 113132.0,
   '2008-02': 112891.5,
   '2008-03': 112417.0,
   '2008-04': 111624.33333333301,
   '2008-05': 110568.66666666699,
   '2008-06': 110205.66666666699,
   '2008-07': 109959.33333333301,
   '2008-08': 109743.33333333301,
   '2008-09': 109070.0,
   '2008-10': 108257.33333333301,
   '2008-11': 107879.66666666699,
   '2008-12': 107375.0,
   '2009-01': 106973.33333333301,
   '2009-02': 106611.66666666699,
   '2009-03': 106582.66666666699,
   '2009-04': 106741.66666666699,
   '2009-05': 106898.0,
   '2009-06': 106916.33333333301,
   '2009-07': 106817.33333333301,
   '2009-08': 106679.0,
   '2009-09': 106597.0,
   '2009-10': 106641.0,
   '2009-11': 106666.33333333301,
   '2009-12': 106836.66666666699,
   '2010-01': 106802.0,
   '2010-02': 106818.66666666699,
   '2010-03': 106586.33333333301,
   '2010-04': 106710.0,
   '2010-05': 106772.66666666699,
   '2010-06': 106827.33333333301,
   '2010-07': 106347.33333333301,
   '2010-08': 105800.33333333301,
   '2010-09': 105189.33333333301,
   '2010-10': 104458.33333333301,
   '2010-11': 103762.0,
   '2010-12': 103041.33333333301,
   '2011-01': 102677.33333333301,
   '2011-02': 101616.0,
   '2011-03': 101080.66666666699,
   '2011-04': 100255.0,
   '2011-05': 99906.6666666667,
   '2011-06': 99059.3333333333,
   '2011-07': 98633.0,
   '2011-08': 98619.6666666667,
   '2011-09': 98966.6666666667,
   '2011-10': 99209.0,
   '2011-11': 99063.3333333333,
   '2011-12': 98774.0,
   '2012-01': 98462.6666666667,
   '2012-02': 98477.3333333333,
   '2012-03': 98404.6666666667,
   '2012-04': 98667.3333333333,
   '2012-05': 99114.0,
   '2012-06': 99777.6666666667,
   '2012-07': 100358.66666666699,
   '2012-08': 100668.33333333301,
   '2012-09': 100900.0,
   '2012-10': 101169.0,
   '2012-11': 101412.66666666699,
   '2012-12': 101586.66666666699,
   '2013-01': 101802.33333333301,
   '2013-02': 102145.66666666699,
   '2013-03': 102837.33333333301,
   '2013-04': 103513.66666666699,
   '2013-05': 104168.33333333301,
   '2013-06': 104674.0,
   '2013-07': 105394.66666666699,
   '2013-08': 106210.33333333301,
   '2013-09': 107187.33333333301,
   '2013-10': 108064.66666666699,
   '2013-11': 108873.66666666699,
   '2013-12': 109624.33333333301,
   '2014-01': 110188.66666666699,
   '2014-02': 110805.66666666699,
   '2014-03': 111483.0,
   '2014-04': 112126.33333333301,
   '2014-05': 112873.66666666699,
   '2014-06': 113574.33333333301,
   '2014-07': 114294.66666666699,
   '2014-08': 114926.33333333301,
   '2014-09': 115229.0,
   '2014-10': 115902.66666666699,
   '2014-11': 116794.33333333301,
   '2014-12': 117979.66666666699,
   '2015-01': 119103.33333333301,
   '2015-02': 120161.33333333301,
   '2015-03': 121246.33333333301,
   '2015-04': 122137.66666666699,
   '2015-05': 123062.33333333301,
   '2015-06': 124129.0,
   '2015-07': 125215.33333333301,
   '2015-08': 126398.0,
   '2015-09': 127324.66666666699,
   '2015-10': 128317.66666666699,
   '2015-11': 129257.33333333301,
   '2015-12': 130386.66666666699,
   '2016-01': 131626.0,
   '2016-02': 132930.333333333,
   '2016-03': 134263.0,
   '2016-04': 135631.0,
   '2016-05': 136980.333333333,
   '2016-06': 138060.666666667,
   '2016-07': 139197.0,
   '2016-08': 140316.333333333,
   '2016-09': 141757.333333333,
   '2016-10': 143032.0,
   '2016-11': 144360.333333333,
   '2016-12': 146036.666666667,
   '2017-01': 147731.666666667,
   '2017-02': 149672.666666667,
   '2017-03': 150839.0,
   '2017-04': 152133.666666667,
   '2017-05': 153226.666666667,
   '2017-06': 154777.666666667,
   '2017-07': 156329.0,
   '2017-08': 157842.333333333,
   '2017-09': 159371.666666667,
   '2017-10': 161186.666666667,
   '2017-11': 162978.0,
   '2017-12': 164437.0,
   '2018-01': 165770.333333333,
   '2018-02': 167267.0,
   '2018-03': 168833.666666667,
   '2018-04': 170089.666666667,
   '2018-05': 170867.666666667,
   '2018-06': 171928.333333333,
   '2018-07': 172943.666666667,
   '2018-08': 173717.333333333,
   '2018-09': 174597.333333333,
   '2018-10': 175531.0,
   '2018-11': 176969.666666667,
   '2018-12': 178518.333333333,
   '2019-01': 180160.0,
   '2019-02': 181227.0,
   '2019-03': 181797.666666667,
   '2019-04': 182062.0,
   '2019-05': 182681.333333333,
   '2019-06': 182909.666666667,
   '2019-07': 183358.666666667,
   '2019-08': 184186.333333333,
   '2019-09': 185607.666666667,
   '2019-10': 186920.333333333,
   '2019-11': 187713.333333333},
  'Four Bedroom Houses': {'2008-01': 175830.0,
   '2008-02': 175203.5,
   '2008-03': 174434.666666667,
   '2008-04': 173246.666666667,
   '2008-05': 171867.0,
   '2008-06': 171458.0,
   '2008-07': 171185.0,
   '2008-08': 171018.333333333,
   '2008-09': 170226.666666667,
   '2008-10': 169126.666666667,
   '2008-11': 168611.333333333,
   '2008-12': 167942.0,
   '2009-01': 167605.666666667,
   '2009-02': 167281.333333333,
   '2009-03': 167391.666666667,
   '2009-04': 167564.666666667,
   '2009-05': 167984.0,
   '2009-06': 168270.666666667,
   '2009-07': 168631.333333333,
   '2009-08': 168755.333333333,
   '2009-09': 168735.333333333,
   '2009-10': 168743.666666667,
   '2009-11': 168738.333333333,
   '2009-12': 169074.0,
   '2010-01': 169076.0,
   '2010-02': 169133.0,
   '2010-03': 168785.666666667,
   '2010-04': 168926.0,
   '2010-05': 168913.333333333,
   '2010-06': 168984.333333333,
   '2010-07': 168457.666666667,
   '2010-08': 167806.333333333,
   '2010-09': 167355.666666667,
   '2010-10': 166613.0,
   '2010-11': 165927.333333333,
   '2010-12': 164929.666666667,
   '2011-01': 164470.0,
   '2011-02': 163056.333333333,
   '2011-03': 162547.333333333,
   '2011-04': 161558.0,
   '2011-05': 161231.333333333,
   '2011-06': 160276.666666667,
   '2011-07': 159959.333333333,
   '2011-08': 160235.0,
   '2011-09': 160860.666666667,
   '2011-10': 161261.333333333,
   '2011-11': 161047.333333333,
   '2011-12': 160676.666666667,
   '2012-01': 160368.0,
   '2012-02': 160818.333333333,
   '2012-03': 160959.666666667,
   '2012-04': 161442.333333333,
   '2012-05': 162018.0,
   '2012-06': 162960.0,
   '2012-07': 163876.0,
   '2012-08': 164338.333333333,
   '2012-09': 164681.0,
   '2012-10': 165067.333333333,
   '2012-11': 165536.666666667,
   '2012-12': 165730.0,
   '2013-01': 166172.333333333,
   '2013-02': 166759.0,
   '2013-03': 167954.0,
   '2013-04': 168934.0,
   '2013-05': 169880.666666667,
   '2013-06': 170627.0,
   '2013-07': 171576.0,
   '2013-08': 172664.333333333,
   '2013-09': 174125.666666667,
   '2013-10': 175530.0,
   '2013-11': 176782.0,
   '2013-12': 177784.0,
   '2014-01': 178463.333333333,
   '2014-02': 179178.333333333,
   '2014-03': 180030.0,
   '2014-04': 180903.0,
   '2014-05': 181883.666666667,
   '2014-06': 182809.666666667,
   '2014-07': 183736.666666667,
   '2014-08': 184769.0,
   '2014-09': 185294.333333333,
   '2014-10': 186350.0,
   '2014-11': 187519.0,
   '2014-12': 189144.333333333,
   '2015-01': 190568.333333333,
   '2015-02': 191994.666666667,
   '2015-03': 193476.666666667,
   '2015-04': 194802.0,
   '2015-05': 196123.0,
   '2015-06': 197611.0,
   '2015-07': 199122.333333333,
   '2015-08': 200695.666666667,
   '2015-09': 201939.333333333,
   '2015-10': 203277.0,
   '2015-11': 204671.0,
   '2015-12': 206363.0,
   '2016-01': 208304.333333333,
   '2016-02': 210112.666666667,
   '2016-03': 211905.666666667,
   '2016-04': 213725.0,
   '2016-05': 215636.666666667,
   '2016-06': 217084.0,
   '2016-07': 218490.666666667,
   '2016-08': 219839.333333333,
   '2016-09': 221632.0,
   '2016-10': 223107.666666667,
   '2016-11': 224629.666666667,
   '2016-12': 226662.333333333,
   '2017-01': 228571.0,
   '2017-02': 230744.0,
   '2017-03': 231813.666666667,
   '2017-04': 233193.0,
   '2017-05': 234291.666666667,
   '2017-06': 235802.333333333,
   '2017-07': 237190.666666667,
   '2017-08': 238686.666666667,
   '2017-09': 240312.333333333,
   '2017-10': 242389.333333333,
   '2017-11': 244281.666666667,
   '2017-12': 245670.333333333,
   '2018-01': 246873.0,
   '2018-02': 248364.0,
   '2018-03': 249972.666666667,
   '2018-04': 251287.333333333,
   '2018-05': 251875.666666667,
   '2018-06': 252703.666666667,
   '2018-07': 253265.666666667,
   '2018-08': 253467.666666667,
   '2018-09': 253857.666666667,
   '2018-10': 254435.666666667,
   '2018-11': 255614.333333333,
   '2018-12': 257159.333333333,
   '2019-01': 258637.333333333,
   '2019-02': 259499.666666667,
   '2019-03': 259619.0,
   '2019-04': 259528.0,
   '2019-05': 259729.666666667,
   '2019-06': 259431.333333333,
   '2019-07': 259315.333333333,
   '2019-08': 259636.333333333,
   '2019-09': 260464.0,
   '2019-10': 261609.333333333,
   '2019-11': 262404.666666667},
  'Five Bedroom Houses': {'2008-01': 233595.0,
   '2008-02': 232899.0,

In [3]:
# An example of the city suggestions being shown for names 

city_example2 = requests.get('https://api.citrics.io/jkekal6d6e5si3i2ld66d4dl/matchcity/fort-worth-tx')
city_example2 = city_example2.json()
city_example2

{'Fort Worth, TX': {'ID': 17417,
  'lat': 32.7812,
  'lng': -97.3472,
  'state': 'Texas',
  'st': 'TX',
  'population': 855786},
 'Wortham, TX': {'ID': 17052,
  'lat': 31.7897,
  'lng': -96.461,
  'state': 'Texas',
  'st': 'TX',
  'population': 1176}}

In [4]:
city_example3 = requests.get('https://api.citrics.io/jkekal6d6e5si3i2ld66d4dl/ip_to_city/136.34.38.43') #Note: IPv4
city_example3 = city_example3.json()
city_example3

{'_id': 9619,
 'name_with_com': 'Kansas City, MO',
 'city_no_st': 'Kansas City',
 'census_full_name': 'Kansas City city, Missouri',
 'City': 'Kansas City MO',
 'State': 'Missouri',
 'st': 'MO',
 'geo_id': '1600000US2938000',
 'Latitude': 39.1239,
 'Longitude': -94.5541,
 'Total Population': 481417.0,
 'Population Male & Female': {'Male': 48.7, 'Female': 51.3},
 'Age Distribution': {'Under 5': 7.0,
  '5 to 9': 6.4,
  '10 to 14': 6.4,
  '15 to 19': 5.6,
  '20 to 24': 7.2,
  '25 to 34': 17.2,
  '35 to 44': 13.2,
  '45 to 54': 12.8,
  '55 to 59': 6.4,
  '60 to 64': 5.6,
  '65 to 74': 7.3,
  '75 to 84': 3.5,
  '85 years and over': 1.7},
 'Median Age': 35.2,
 'Population under 18': 23.1,
 'Population over 16': 79.1,
 'Ethnicity': {'White': 55.5,
  'Hispanic or Latino': 10.2,
  'African American': 28.5,
  'American Indian': 0.3,
  'Asian': 2.7,
  'Pacific Islander': 0.1,
  'other race': 0.2,
  'Two or more races': 2.6},
 'Marital Status': {'Males': {'Never Married': 42.2,
   'Currently Married': 41.7,
   'Separated': 1.9,
   'Divorced': 2.6},
  'Females': {'Never Married': 37.4,
   'Currently Married': 37.7,
   'Separated': 2.3,
   'Divorced': 8.1}},
 'Recent Mothers': {'Total': 6927.0,
  'Birth Rate': {'Avg': 56.0},
  'Age Distribution': {'15-19': 13.0, '20-34': 88.0, '35-50': 31.0},
  'National Avg': {'15-19': 17.29, '20-34': 103.95, '35-50': 19.82}},
 'School Enrollment': {'Preschool': 5.3,
  'Elementary': 41.7,
  'High school': 18.3,
  'College': 28.1},
 'Educational Attainment': {'Less than 9th grade': 3.7,
  '9th to 12th grade no diploma': 7.2,
  'High school': 26.0,
  'Some college no degree': 22.4,
  "Associate's degree": 7.3,
  "Bachelor's degree": 20.9,
  'Graduate degree': 12.6},
 'Language': {'English Only': 88.0,
  'Language other than English': 12.0,
  'Cannot Speak English': 5.1},
 'Two or more Languages': 6.9,
 'Unemployment Rate': 5.9,
 'Sex of Labor Force': {'Male': 35.5, 'Female': 64.5},
 'Commuting to Work': {'Drives Alone': 80.4,
  'Carpools': 8.4,
  'Public Transport': 2.9,
  'Walks': 2.1,
  'Works at home': 4.8,
  'Other transport': 1.4},
 'Mean Travel Time': 21.8,
 'Occupation': {'Management business science and arts occupations': 38.6,
  'Service occupations': 18.5,
  'Sales and office occupations': 24.3,
  'Natural resources construction and maintenance occupations': 6.5},
 'Industry': {'Agriculture forestry fishing and hunting and mining': 0.4,
  'Construction': 5.0,
  'Manufacturing': 8.0,
  'Wholesale trade': 2.5,
  'Retail trade': 10.9,
  'Transportation and warehousing and utilities': 6.1,
  'Information': 2.7,
  'Finance and insurance and real estate and rental and leasing': 7.7,
  'Professional scientific and management and administrative and waste management services': 14.4,
  'Educational services and health care and social assistance': 22.7,
  'Arts entertainment and recreation and accommodation and food services': 10.6,
  'Other services except public administration': 4.3,
  'Public administration': 4.8},
 'Class of Worker': {'Private wage and salary workers': 83.1,
  'Government workers': 11.9,
  'Self-employed in own not incorporated business workers': 4.8,
  'Unpaid family workers': 0.2},
 'Household Income': {'Less than USD 10,000': 8.3,
  'USD 10,000 - USD 14,999': 5.6,
  'USD 15,000 - USD 24,999': 11.2,
  'USD 25,000 - USD 34,999': 10.6,
  'USD 35,000 - USD 49,999': 14.1,
  'USD 50,000 - USD 74,999': 18.4,
  'USD 75,000 - USD 99,999': 11.7,
  'USD 100,000 - USD 149,999': 11.8,
  'USD 150,000 - USD 199,999': 4.4,
  'USD 200,000 or more': 3.8},
 'Median Household Income': 50136.0,
 'Mean Household Income': 68949.0,
 'Retirement Percent': {'With Social Security': 25.4,
  'With retirement income': 16.1,
  'With Supplemental Security Income': 5.5},
 'Retirement Avg': {'Mean Social Security income': 17775.0,
  'Mean retirement income': 23598.0,
  'Mean Supplemental Security Income': 9796.0},
 'Public Assistance Percent': {'With cash public assistance income': 3.0,
  'With Food Stamp/SNAP benefits': 13.8},
 'Median Per Capita Income': 32119.0,
 'Per Capita by Gender': {'Female': 39425.0, 'Male': 46772.0},
 'Health Insurance': 86.7,
 'Below Poverty Level': 12.7,
 'Total Housing Units': 229508.0,
 'Occupied Housing Units': {'Occupied Housing Units': 86.7,
  'Vacant Housing Units': 13.3},
 'Vacancy Rate': {'Homeowner vacancy rate': 2.1, 'Rental vacancy rate': 7.1},
 'Units in Structure': {'1-unit detached': 63.0,
  '1-unit attached': 4.6,
  '2 units': 2.5,
  '3 - 4 units': 4.7,
  '5 - 9 units': 6.4,
  '10 - 19 units': 5.9,
  '20 or more units': 12.0},
 'Total Housing units': 229508.0,
 'Year Built': {'2014 or later': 0.9,
  '2010 - 2013': 2.0,
  '2000 - 2009': 10.6,
  '1990 - 1999': 9.2,
  '1980 - 1989': 8.5,
  '1970 - 1979': 12.3,
  '1960 - 1969': 13.6,
  '1950 - 1959': 14.7,
  '1940 - 1949': 6.8,
  '1939 or earlier': 21.4},
 'Housing by rooms': {'1 room': 2.1,
  '2 rooms': 3.3,
  '3 rooms': 9.6,
  '4 rooms': 14.4,
  '5 rooms': 20.5,
  '6 rooms': 19.2,
  '7 rooms': 12.7,
  '8 rooms': 7.8,
  '9 rooms or more': 10.3},
 'Housing by bedrooms': {'No bedrooms': 2.3,
  '1 bedroom': 14.8,
  '2 bedrooms': 28.2,
  '3 bedrooms': 37.2,
  '4 bedrooms': 14.1,
  '5 bedrooms or more': 3.5},
 'Year Moved in': {'2015 or later': 14.6,
  '2010 - 2014': 37.3,
  '2000 - 2009': 25.9,
  '1990 - 1999': 10.4,
  '1980 - 1989': 5.3,
  '1979 and earlier': 6.5},
 'Occupants per room': {'1 or less': 98.3,
  '1 to one and a half ': 1.1,
  'one and a half or more': 0.5},
 'Vehicles Available': {'No vehicles available': 10.4,
  '1 vehicle available': 41.1,
  '2 vehicles available': 34.2,
  '3 or more vehicles available': 14.3},
 'Selected Monthly Owner Costs with Mortgage': {'Less than USD 500': 1.5,
  'USD 500 - USD 999': 24.0,
  'USD 1,000 - USD 1,499': 37.9,
  'USD 1,500 - USD 1,999': 20.3,
  'USD 2,000 - USD 2,499': 9.4,
  'USD 2,500 - USD 2,999': 3.5,
  'USD 3,000 or more': 3.5},
 'Median Selected Monthly Owner Costs with Mortgage': 1318.0,
 'Selected Monthly Owner Costs without Mortgage': {'Less than USD 250': 9.4,
  'USD 250 - USD 399': 27.4,
  'USD 400 - USD 599': 35.9,
  'USD 600 - USD 799': 16.9,
  'USD 800 - USD 999': 6.0,
  'USD 1,000 or more': 4.4},
 'Median Selected Monthly Owner Costs without Mortgage': 463.0,
 'Rent': {'Less than USD 500': 10.7,
  'USD 500 - USD 999': 55.4,
  'USD 1,000 - USD 1,499': 27.3,
  'USD 1,500 - USD 1,999': 4.7,
  'USD 2,000 - USD 2,499': 1.3,
  'USD 2,500 - USD 2,999': 0.2,
  'USD 3,000 or more': 0.5},
 'Median Rent': 862.0,
 'Population Growth': {'2010': 454876.0,
  '2011': 457551.0,
  '2012': 459772.0,
  '2013': 462378.0,
  '2014': 465005.0,
  '2015': 467990.0,
  '2016': 471767.0,
  '2017': 476974.0,
  '2018': 481417.0},
 'housing_helper': {'note': 'Property value data for Kansas City MO provided by Zillow.',
  'no_zillow_city_data': False,
  'all_city_data_available': True,
  'all_bedroom_data_present': True,
  'includes_1bed': True,
  'includes_2bed': True,
  'includes_3bed': True,
  'includes_4bed': True,
  'includes_5bed': True,
  'includes_avgallhomes': True},
 'Historical Property Value Data': {'One Bedroom Houses': {'2008-01': 112839.0,
   '2008-02': 112980.0,
   '2008-03': 112602.0,
   '2008-04': 111640.0,
   '2008-05': 110668.0,
   '2008-06': 109353.66666666699,
   '2008-07': 108416.0,
   '2008-08': 107374.0,
   '2008-09': 107338.66666666699,
   '2008-10': 107049.66666666699,
   '2008-11': 106420.0,
   '2008-12': 105385.0,
   '2009-01': 104793.66666666699,
   '2009-02': 104558.0,
   '2009-03': 104040.33333333301,
   '2009-04': 103290.0,
   '2009-05': 102323.66666666699,
   '2009-06': 101661.66666666699,
   '2009-07': 101242.0,
   '2009-08': 101313.33333333301,
   '2009-09': 101327.0,
   '2009-10': 100870.0,
   '2009-11': 100660.33333333301,
   '2009-12': 100288.66666666699,
   '2010-01': 99655.6666666667,
   '2010-02': 98589.6666666667,
   '2010-03': 98418.3333333333,
   '2010-04': 98568.6666666667,
   '2010-05': 98618.6666666667,
   '2010-06': 97797.3333333333,
   '2010-07': 96996.3333333333,
   '2010-08': 96216.3333333333,
   '2010-09': 95099.3333333333,
   '2010-10': 93989.0,
   '2010-11': 92308.0,
   '2010-12': 91361.0,
   '2011-01': 90658.6666666667,
   '2011-02': 90495.3333333333,
   '2011-03': 90066.0,
   '2011-04': 89802.3333333333,
   '2011-05': 89325.3333333333,
   '2011-06': 88887.0,
   '2011-07': 88220.6666666667,
   '2011-08': 87425.3333333333,
   '2011-09': 86656.3333333333,
   '2011-10': 86446.0,
   '2011-11': 86748.0,
   '2011-12': 87090.3333333333,
   '2012-01': 87384.0,
   '2012-02': 86983.3333333333,
   '2012-03': 86966.3333333333,
   '2012-04': 86840.6666666667,
   '2012-05': 87296.3333333333,
   '2012-06': 87401.0,
   '2012-07': 87539.6666666667,
   '2012-08': 87744.6666666667,
   '2012-09': 87982.3333333333,
   '2012-10': 87549.0,
   '2012-11': 87083.3333333333,
   '2012-12': 86659.3333333333,
   '2013-01': 87403.6666666667,
   '2013-02': 88129.6666666667,
   '2013-03': 88981.3333333333,
   '2013-04': 89463.6666666667,
   '2013-05': 90157.6666666667,
   '2013-06': 91330.6666666667,
   '2013-07': 92194.0,
   '2013-08': 92932.6666666667,
   '2013-09': 93097.6666666667,
   '2013-10': 93622.6666666667,
   '2013-11': 94082.6666666667,
   '2013-12': 94807.3333333333,
   '2014-01': 95308.0,
   '2014-02': 95448.6666666667,
   '2014-03': 95200.3333333333,
   '2014-04': 95292.3333333333,
   '2014-05': 95781.6666666667,
   '2014-06': 96400.0,
   '2014-07': 96692.0,
   '2014-08': 97208.3333333333,
   '2014-09': 97829.6666666667,
   '2014-10': 98630.0,
   '2014-11': 99403.0,
   '2014-12': 99787.6666666667,
   '2015-01': 99833.0,
   '2015-02': 99565.0,
   '2015-03': 99770.0,
   '2015-04': 99848.3333333333,
   '2015-05': 100050.66666666699,
   '2015-06': 100355.66666666699,
   '2015-07': 100847.33333333301,
   '2015-08': 101084.0,
   '2015-09': 101325.33333333301,
   '2015-10': 101830.0,
   '2015-11': 102573.66666666699,
   '2015-12': 103028.0,
   '2016-01': 102946.66666666699,
   '2016-02': 103207.33333333301,
   '2016-03': 103819.66666666699,
   '2016-04': 105024.66666666699,
   '2016-05': 105824.0,
   '2016-06': 106605.0,
   '2016-07': 107233.66666666699,
   '2016-08': 108185.33333333301,
   '2016-09': 108719.66666666699,
   '2016-10': 109158.33333333301,
   '2016-11': 109175.0,
   '2016-12': 109666.33333333301,
   '2017-01': 110331.66666666699,
   '2017-02': 111144.33333333301,
   '2017-03': 111704.0,
   '2017-04': 112135.0,
   '2017-05': 112529.0,
   '2017-06': 112771.66666666699,
   '2017-07': 113251.66666666699,
   '2017-08': 113625.66666666699,
   '2017-09': 114758.66666666699,
   '2017-10': 116062.0,
   '2017-11': 117627.66666666699,
   '2017-12': 118676.66666666699,
   '2018-01': 119271.66666666699,
   '2018-02': 120271.0,
   '2018-03': 120785.66666666699,
   '2018-04': 121396.0,
   '2018-05': 121616.0,
   '2018-06': 122052.66666666699,
   '2018-07': 122246.66666666699,
   '2018-08': 122223.66666666699,
   '2018-09': 122220.66666666699,
   '2018-10': 122509.33333333301,
   '2018-11': 122967.33333333301,
   '2018-12': 123621.33333333301,
   '2019-01': 124196.33333333301,
   '2019-02': 124642.0,
   '2019-03': 124580.66666666699,
   '2019-04': 124435.33333333301,
   '2019-05': 124192.33333333301,
   '2019-06': 124711.0,
   '2019-07': 125731.66666666699,
   '2019-08': 126600.66666666699,
   '2019-09': 127105.66666666699,
   '2019-10': 127338.0,
   '2019-11': 127709.33333333301},
  'Two Bedroom Houses': {'2008-01': 88794.0,
   '2008-02': 88809.0,
   '2008-03': 88227.0,
   '2008-04': 86891.3333333333,
   '2008-05': 85078.0,
   '2008-06': 83569.0,
   '2008-07': 82617.0,
   '2008-08': 81840.3333333333,
   '2008-09': 80855.6666666667,
   '2008-10': 79559.3333333333,
   '2008-11': 77898.6666666667,
   '2008-12': 76051.0,
   '2009-01': 74193.0,
   '2009-02': 72578.3333333333,
   '2009-03': 71118.0,
   '2009-04': 69908.3333333333,
   '2009-05': 68536.3333333333,
   '2009-06': 67234.6666666667,
   '2009-07': 66033.3333333333,
   '2009-08': 65193.6666666667,
   '2009-09': 64651.3333333333,
   '2009-10': 64326.0,
   '2009-11': 64316.6666666667,
   '2009-12': 64182.0,
   '2010-01': 63557.6666666667,
   '2010-02': 63026.3333333333,
   '2010-03': 62729.0,
   '2010-04': 62828.0,
   '2010-05': 62503.0,
   '2010-06': 62068.0,
   '2010-07': 61388.3333333333,
   '2010-08': 60981.6666666667,
   '2010-09': 60617.6666666667,
   '2010-10': 60350.0,
   '2010-11': 59816.0,
   '2010-12': 59236.6666666667,
   '2011-01': 58761.6666666667,
   '2011-02': 58499.0,
   '2011-03': 58231.6666666667,
   '2011-04': 57868.0,
   '2011-05': 57371.3333333333,
   '2011-06': 56905.3333333333,
   '2011-07': 56289.0,
   '2011-08': 55650.6666666667,
   '2011-09': 55050.3333333333,
   '2011-10': 54641.3333333333,
   '2011-11': 54427.0,
   '2011-12': 54399.6666666667,
   '2012-01': 54340.3333333333,
   '2012-02': 53859.0,
   '2012-03': 53389.6666666667,
   '2012-04': 53051.3333333333,
   '2012-05': 52935.6666666667,
   '2012-06': 52766.0,
   '2012-07': 52903.6666666667,
   '2012-08': 53089.0,
   '2012-09': 53217.6666666667,
   '2012-10': 52754.3333333333,
   '2012-11': 52434.0,
   '2012-12': 52224.0,
   '2013-01': 52675.6666666667,
   '2013-02': 53060.6666666667,
   '2013-03': 53331.3333333333,
   '2013-04': 53341.6666666667,
   '2013-05': 53624.0,
   '2013-06': 53845.6666666667,
   '2013-07': 53762.6666666667,
   '2013-08': 53378.0,
   '2013-09': 52961.3333333333,
   '2013-10': 52923.0,
   '2013-11': 53207.3333333333,
   '2013-12': 53770.0,
   '2014-01': 54150.0,
   '2014-02': 54249.0,
   '2014-03': 54362.0,
   '2014-04': 54613.3333333333,
   '2014-05': 54963.3333333333,
   '2014-06': 55236.0,
   '2014-07': 55360.6666666667,
   '2014-08': 55500.3333333333,
   '2014-09': 55727.3333333333,
   '2014-10': 56193.0,
   '2014-11': 56725.6666666667,
   '2014-12': 57131.0,
   '2015-01': 57424.3333333333,
   '2015-02': 57622.3333333333,
   '2015-03': 58050.0,
   '2015-04': 58424.3333333333,
   '2015-05': 58922.3333333333,
   '2015-06': 59379.6666666667,
   '2015-07': 59926.3333333333,
   '2015-08': 60308.6666666667,
   '2015-09': 60566.6666666667,
   '2015-10': 60911.6666666667,
   '2015-11': 61246.0,
   '2015-12': 61307.6666666667,
   '2016-01': 61254.6666666667,
   '2016-02': 61267.0,
   '2016-03': 61446.0,
   '2016-04': 61702.0,
   '2016-05': 62210.0,
   '2016-06': 62896.3333333333,
   '2016-07': 63616.6666666667,
   '2016-08': 64449.6666666667,
   '2016-09': 65269.0,
   '2016-10': 66004.3333333333,
   '2016-11': 66245.0,
   '2016-12': 66654.3333333333,
   '2017-01': 67206.6666666667,
   '2017-02': 68061.0,
   '2017-03': 68785.3333333333,
   '2017-04': 69449.3333333333,
   '2017-05': 70213.3333333333,
   '2017-06': 71046.0,
   '2017-07': 72034.6666666667,
   '2017-08': 72793.0,
   '2017-09': 73696.6666666667,
   '2017-10': 74557.0,
   '2017-11': 75560.6666666667,
   '2017-12': 76393.6666666667,
   '2018-01': 77371.3333333333,
   '2018-02': 78342.0,
   '2018-03': 79223.0,
   '2018-04': 80098.3333333333,
   '2018-05': 80979.0,
   '2018-06': 81717.3333333333,
   '2018-07': 82350.6666666667,
   '2018-08': 83156.6666666667,
   '2018-09': 84069.6666666667,
   '2018-10': 84773.3333333333,
   '2018-11': 85301.6666666667,
   '2018-12': 85928.3333333333,
   '2019-01': 86733.0,
   '2019-02': 87406.3333333333,
   '2019-03': 87777.6666666667,
   '2019-04': 88026.6666666667,
   '2019-05': 88264.3333333333,
   '2019-06': 88636.3333333333,
   '2019-07': 89088.3333333333,
   '2019-08': 89343.0,
   '2019-09': 89409.3333333333,
   '2019-10': 89510.0,
   '2019-11': 89680.0},
  'Three Bedroom Houses': {'2008-01': 126960.0,
   '2008-02': 126983.5,
   '2008-03': 126698.33333333301,
   '2008-04': 126137.0,
   '2008-05': 125528.33333333301,
   '2008-06': 124851.0,
   '2008-07': 123972.33333333301,
   '2008-08': 122991.33333333301,
   '2008-09': 122402.66666666699,
   '2008-10': 121994.0,
   '2008-11': 121372.66666666699,
   '2008-12': 120488.66666666699,
   '2009-01': 119866.66666666699,
   '2009-02': 119081.0,
   '2009-03': 118276.33333333301,
   '2009-04': 117223.0,
   '2009-05': 116476.33333333301,
   '2009-06': 115624.33333333301,
   '2009-07': 115149.33333333301,
   '2009-08': 115163.33333333301,
   '2009-09': 115515.66666666699,
   '2009-10': 115757.0,
   '2009-11': 116093.66666666699,
   '2009-12': 116348.0,
   '2010-01': 115957.0,
   '2010-02': 115536.33333333301,
   '2010-03': 115525.0,
   '2010-04': 116012.66666666699,
   '2010-05': 116085.33333333301,
   '2010-06': 115576.66666666699,
   '2010-07': 114780.66666666699,
   '2010-08': 113770.33333333301,
   '2010-09': 112590.33333333301,
   '2010-10': 111597.66666666699,
   '2010-11': 110066.33333333301,
   '2010-12': 108924.33333333301,
   '2011-01': 107836.33333333301,
   '2011-02': 107288.66666666699,
   '2011-03': 106376.33333333301,
   '2011-04': 105139.66666666699,
   '2011-05': 103754.33333333301,
   '2011-06': 102494.33333333301,
   '2011-07': 101699.66666666699,
   '2011-08': 101000.0,
   '2011-09': 100231.0,
   '2011-10': 99367.6666666667,
   '2011-11': 98917.0,
   '2011-12': 98557.0,
   '2012-01': 98133.3333333333,
   '2012-02': 97532.6666666667,
   '2012-03': 97292.3333333333,
   '2012-04': 97321.6666666667,
   '2012-05': 97207.3333333333,
   '2012-06': 96996.6666666667,
   '2012-07': 96903.0,
   '2012-08': 97001.3333333333,
   '2012-09': 97135.3333333333,
   '2012-10': 97097.3333333333,
   '2012-11': 97127.3333333333,
   '2012-12': 97299.3333333333,
   '2013-01': 97348.0,
   '2013-02': 97567.3333333333,
   '2013-03': 97724.6666666667,
   '2013-04': 98008.0,
   '2013-05': 98497.3333333333,
   '2013-06': 99592.0,
   '2013-07': 100784.0,
   '2013-08': 101428.33333333301,
   '2013-09': 101508.0,
   '2013-10': 101633.66666666699,
   '2013-11': 102136.66666666699,
   '2013-12': 102581.0,
   '2014-01': 103199.66666666699,
   '2014-02': 103222.66666666699,
   '2014-03': 102999.0,
   '2014-04': 102851.33333333301,
   '2014-05': 103145.66666666699,
   '2014-06': 103812.66666666699,
   '2014-07': 104083.33333333301,
   '2014-08': 104555.0,
   '2014-09': 104867.33333333301,
   '2014-10': 105361.66666666699,
   '2014-11': 105938.33333333301,
   '2014-12': 106343.66666666699,
   '2015-01': 106586.66666666699,
   '2015-02': 106537.66666666699,
   '2015-03': 107021.66666666699,
   '2015-04': 107667.0,
   '2015-05': 108415.33333333301,
   '2015-06': 109038.33333333301,
   '2015-07': 109667.66666666699,
   '2015-08': 110008.33333333301,
   '2015-09': 110318.33333333301,
   '2015-10': 110695.0,
   '2015-11': 111260.0,
   '2015-12': 111643.66666666699,
   '2016-01': 112184.33333333301,
   '2016-02': 112918.66666666699,
   '2016-03': 113967.66666666699,
   '2016-04': 114911.33333333301,
   '2016-05': 115989.66666666699,
   '2016-06': 116923.66666666699,
   '2016-07': 117820.0,
   '2016-08': 118904.66666666699,
   '2016-09': 119924.66666666699,
   '2016-10': 121041.0,
   '2016-11': 121813.0,
   '2016-12': 122757.0,
   '2017-01': 123834.66666666699,
   '2017-02': 125204.0,
   '2017-03': 126372.33333333301,
   '2017-04': 127308.33333333301,
   '2017-05': 128026.33333333301,
   '2017-06': 128890.66666666699,
   '2017-07': 129980.33333333301,
   '2017-08': 130960.66666666699,
   '2017-09': 132246.333333333,
   '2017-10': 133369.333333333,
   '2017-11': 134561.0,
   '2017-12': 135533.333333333,
   '2018-01': 136869.0,
   '2018-02': 138195.0,
   '2018-03': 139348.666666667,
   '2018-04': 140552.666666667,
   '2018-05': 141650.0,
   '2018-06': 142647.333333333,
   '2018-07': 143244.333333333,
   '2018-08': 144083.333333333,
   '2018-09': 145049.333333333,
   '2018-10': 145901.666666667,
   '2018-11': 146522.0,
   '2018-12': 147357.0,
   '2019-01': 148345.0,
   '2019-02': 149490.333333333,
   '2019-03': 150163.0,
   '2019-04': 150700.333333333,
   '2019-05': 151052.333333333,
   '2019-06': 151290.333333333,
   '2019-07': 151555.666666667,
   '2019-08': 151831.333333333,
   '2019-09': 152309.666666667,
   '2019-10': 152771.666666667,
   '2019-11': 153168.666666667},
  'Four Bedroom Houses': {'2008-01': 202517.0,
   '2008-02': 202559.0,
   '2008-03': 202207.0,
   '2008-04': 201500.333333333,