In [1]:
import numpy as np
import pandas as pd

In [163]:
uscb = pd.read_csv('all_census_data.csv')

In [164]:
uscb = uscb.drop(index = 0) # drop first row

In [167]:
uscb = uscb[['NAME', 'DP05_0001E']]

In [168]:
# Make a new column with just the city name
uscb['City'] = uscb['NAME'].str.split(",", n = 1, expand=True)[0]

# Make a new column with just the state name
uscb['State'] = uscb['NAME'].str.split(",", n = 1, expand=True)[1]
uscb['State'] = uscb['State'].str.lstrip()

# Mark which type of 'place' each city is deamded to be by the US Census Bureau
uscb['Place_Type_city'] = uscb['City'].str.contains(pat = ' city')
uscb['Place_Type_town'] = uscb['City'].str.contains(pat = ' town')
uscb['Place_Type_borough'] = uscb['City'].str.contains(pat = ' borough')
uscb['Place_Type_CPD'] = uscb['City'].str.contains(pat = ' CDP')

# Remove that place type from the city name
uscb['City'] = uscb['City'].str.replace(' city', '', regex=False)
uscb['City'] = uscb['City'].str.replace(' town', '', regex=False)
uscb['City'] = uscb['City'].str.replace(' borough', '', regex=False)
uscb['City'] = uscb['City'].str.replace(' CDP', '', regex=False)
uscb['City'] = uscb['City'].str.rstrip()

C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # Remove the CWD from sys.path while we load stuff.
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  # This is added back by InteractiveShellApp.init_path()
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if sys.path[0] == '':
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [169]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'District of Columbia': 'DC',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Northern Mariana Islands':'MP',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Palau': 'PW',
    'Pennsylvania': 'PA',
    'Puerto Rico': 'PR',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virgin Islands': 'VI',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}

In [170]:
# Make a state abbrevations column with the dictionary above
uscb['State_Abbrev'] = uscb['State'].map(us_state_abbrev)

# Make the column we'll use as the primary key to match up datasets, City_ST
uscb['City_ST'] = uscb['City'] + " " + uscb['State_Abbrev']

C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\ltown\Anaconda3\envs\unit2\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [171]:
uscb.head()

,NAME,DP05_0001E,City,State,Place_Type_city,Place_Type_town,Place_Type_borough,Place_Type_CPD,State_Abbrev,City_ST
1,"Russellville city, Alabama",9715,Russellville,Alabama,True,False,False,False,AL,Russellville AL
2,"Vina town, Alabama",327,Vina,Alabama,False,True,False,False,AL,Vina AL
3,"Providence town, Alabama",221,Providence,Alabama,False,True,False,False,AL,Providence AL
4,"Grant town, Alabama",1017,Grant,Alabama,False,True,False,False,AL,Grant AL
5,"Daviston town, Alabama",238,Daviston,Alabama,False,True,False,False,AL,Daviston AL

In [172]:
uscb.shape

(29314, 10)

In [173]:
uscb.nunique()

NAME                  29314
DP05_0001E            10160
City                  20922
State                    53
Place_Type_city           2
Place_Type_town           2
Place_Type_borough        2
Place_Type_CPD            2
State_Abbrev             51
City_ST               29237
dtype: int64

In [174]:
# The count of total rows =/= to the number unique values in City_ST, find duplicates
dups = 29314 - 29237
dups

77

In [192]:
# The count of total rows =/= to the number unique values in City_ST, find duplicates

uscb.City_ST.value_counts()

Agua Dulce TX                    2
St. Johns AZ                     2
Elgin SC                         2
Bel Air MD                       2
Sulphur Springs AR               2
Los Fresnos TX                   2
Riverside PA                     2
Prospect Park PA                 2
Salem AR                         2
Twin Lakes MN                    2
Santa Anna TX                    2
Allenport PA                     2
Midway PA                        2
Santa Rosa TX                    2
Westwood KY                      2
Mahnomen MN                      2
Oklahoma PA                      2
Mountain View WY                 2
Morrisville PA                   2
Burbank CA                       2
Live Oak CA                      2
Rice Lake MN                     2
Unionville PA                    2
Liberty OK                       2
Franklin PA                      2
Marietta OK                      2
Georgetown IL                    2
Elbow Lake MN                    2
Newtown PA                       2
Brownstown PA                    2
                                ..
Mount Pulaski IL                 1
Forestville village MI           1
Battle Mountain NV               1
Pimmit Hills VA                  1
Attalla AL                       1
Fox Lake MT                      1
Highmore SD                      1
Cornwall-on-Hudson village NY    1
Port Alexander AK                1
South Bound Brook NJ             1
Beechwood Village KY             1
Presho SD                        1
Chester Gap VA                   1
North Arlington NJ               1
Monrovia MD                      1
Excelsior Estates village MO     1
Wheatland MO                     1
Cambria CA                       1
Bellerose village NY             1
Blue Springs AL                  1
Brentford SD                     1
West DeLand FL                   1
Fidelity MO                      1
Hollowayville village IL         1
Florida Ridge FL                 1
Circle D-KC Estates TX           1
Latah WA                         1
B and E TX                       1
Renner Corner SD                 1
Augusta KS                       1
Name: City_ST, Length: 29237, dtype: int64

,NAME,DP05_0001E,City,State,Place_Type_city,Place_Type_town,Place_Type_borough,Place_Type_CPD,State_Abbrev,City_ST,dups
1,"Russellville city, Alabama",9715,Russellville,Alabama,True,False,False,False,AL,Russellville AL,NaN
2,"Vina town, Alabama",327,Vina,Alabama,False,True,False,False,AL,Vina AL,NaN
3,"Providence town, Alabama",221,Providence,Alabama,False,True,False,False,AL,Providence AL,NaN
4,"Grant town, Alabama",1017,Grant,Alabama,False,True,False,False,AL,Grant AL,NaN
5,"Daviston town, Alabama",238,Daviston,Alabama,False,True,False,False,AL,Daviston AL,NaN

In [195]:
test = uscb[uscb.City_ST == 'Santa Rosa TX']

In [196]:
test

,NAME,DP05_0001E,City,State,Place_Type_city,Place_Type_town,Place_Type_borough,Place_Type_CPD,State_Abbrev,City_ST,dups
24859,"Santa Rosa town, Texas",2843,Santa Rosa,Texas,False,True,False,False,TX,Santa Rosa TX,29312
25057,"Santa Rosa CDP, Texas",181,Santa Rosa,Texas,False,False,False,True,TX,Santa Rosa TX,29312

In [150]:
uscities = pd.read_csv('uscities.csv')

In [151]:
uscities = uscities[['city', 'state_id', 'lat', 'lng']]
# new = old.filter(['A','B','D'], axis=1)

In [152]:
uscities.head()

           city state_id      lat       lng
0   South Creek       WA  46.9994 -122.3921
1        Roslyn       WA  47.2507 -121.0989
2       Sprague       WA  47.3048 -117.9713
3    Gig Harbor       WA  47.3352 -122.5968
4  Lake Cassidy       WA  48.0639 -122.0920

In [153]:
# Make the column we'll use as the primary key to match up datasets, City_ST
uscities['City_ST'] = uscities['city'] + " " + uscities['state_id']

In [154]:
uscities.shape

(28889, 5)

In [155]:
uscities.nunique()

city        19387
state_id       52
lat         26585
lng         27843
City_ST     28889
dtype: int64

In [156]:
df = pd.merge(uscb_1, uscities, how='inner', on='City_ST')

In [157]:
df.shape

(24516, 13)

In [158]:
df.isnull().sum(axis = 0)

NAME                  0
State                 0
City                  0
Place_Type_city       0
Place_Type_town       0
Place_Type_borough    0
Place_Type_CPD        0
State_Abbrev          0
City_ST               0
city                  0
state_id              0
lat                   0
lng                   0
dtype: int64

In [112]:
df

,NAME,State,City,Place_Type_city,Place_Type_town,Place_Type_borough,Place_Type_CPD,State_Abbrev,City_ST,city,state_id,lat,lng
0,"Russellville city, Alabama",Alabama,Russellville,True,False,False,False,AL,Russellville AL,Russellville,AL,34.5056,-87.7282
1,"Vina town, Alabama",Alabama,Vina,False,True,False,False,AL,Vina AL,Vina,AL,34.3757,-88.0602
2,"Providence town, Alabama",Alabama,Providence,False,True,False,False,AL,Providence AL,Providence,AL,32.3424,-87.7761
3,"Grant town, Alabama",Alabama,Grant,False,True,False,False,AL,Grant AL,Grant,AL,34.5189,-86.2492
4,"Daviston town, Alabama",Alabama,Daviston,False,True,False,False,AL,Daviston AL,Daviston,AL,33.0557,-85.6371
5,"Clanton city, Alabama",Alabama,Clanton,True,False,False,False,AL,Clanton AL,Clanton,AL,32.8439,-86.6230
6,"Gurley town, Alabama",Alabama,Gurley,False,True,False,False,AL,Gurley AL,Gurley,AL,34.7072,-86.3768
7,"Moores Mill CDP, Alabama",Alabama,Moores Mill,False,False,False,True,AL,Moores Mill AL,Moores Mill,AL,34.8491,-86.5222
8,"New Hope city, Alabama",Alabama,New Hope,True,False,False,False,AL,New Hope AL,New Hope,AL,34.5370,-86.4128
9,"New Market CDP, Alabama",Alabama,New Market,False,False,False,True,AL,New Market AL,New Market,AL,34.8892,-86.4226
10,"Hurtsboro town, Alabama",Alabama,Hurtsboro,False,True,False,False,AL,Hurtsboro AL,Hurtsboro,AL,32.2401,-85.4147
11,"Haleburg town, Alabama",Alabama,Haleburg,False,True,False,False,AL,Haleburg AL,Haleburg,AL,31.4099,-85.1381
12,"Newville town, Alabama",Alabama,Newville,False,True,False,False,AL,Newville AL,Newville,AL,31.4206,-85.3367
13,"Louisville town, Alabama",Alabama,Louisville,False,True,False,False,AL,Louisville AL,Louisville,AL,31.7810,-85.5583
14,"Orrville town, Alabama",Alabama,Orrville,False,True,False,False,AL,Orrville AL,Orrville,AL,32.3068,-87.2454
15,"Cuba town, Alabama",Alabama,Cuba,False,True,False,False,AL,Cuba AL,Cuba,AL,32.4410,-88.3755
16,"Gainesville town, Alabama",Alabama,Gainesville,False,True,False,False,AL,Gainesville AL,Gainesville,AL,32.8149,-88.1608
17,"Alabaster city, Alabama",Alabama,Alabaster,True,False,False,False,AL,Alabaster AL,Alabaster,AL,33.2198,-86.8226
18,"Harpersville town, Alabama",Alabama,Harpersville,False,True,False,False,AL,Harpersville AL,Harpersville,AL,33.3184,-86.4287
19,"Gantt town, Alabama",Alabama,Gantt,False,True,False,False,AL,Gantt AL,Gantt,AL,31.4092,-86.4842
20,"Libertyville town, Alabama",Alabama,Libertyville,False,True,False,False,AL,Libertyville AL,Libertyville,AL,31.2428,-86.4599
21,"Glen Allen town, Alabama",Alabama,Glen Allen,False,True,False,False,AL,Glen Allen AL,Glen Allen,AL,33.8922,-87.7328
22,"Franklin town, Alabama",Alabama,Franklin,False,True,False,False,AL,Franklin AL,Franklin,AL,32.4551,-85.8066
23,"Blue Springs town, Alabama",Alabama,Blue Springs,False,True,False,False,AL,Blue Springs AL,Blue Springs,AL,31.6635,-85.5035
24,"Hobson City town, Alabama",Alabama,Hobson City,False,True,False,False,AL,Hobson City AL,Hobson City,AL,33.6149,-85.8560
25,"Cottonwood town, Alabama",Alabama,Cottonwood,False,True,False,False,AL,Cottonwood AL,Cottonwood,AL,31.0552,-85.3007
26,"Chickasaw city, Alabama",Alabama,Chickasaw,True,False,False,False,AL,Chickasaw AL,Chickasaw,AL,30.7715,-88.0793
27,"Saraland city, Alabama",Alabama,Saraland,True,False,False,False,AL,Saraland AL,Saraland,AL,30.8457,-88.0990
28,"Cordova city, Alabama",Alabama,Cordova,True,False,False,False,AL,Cordova AL,Cordova,AL,33.7613,-87.1926
29,"Parrish town, Alabama",Alabama,Parrish,False,True,False,False,AL,Parrish AL,Parrish,AL,33.7323,-87.2802
...,...,...,...,...,...,...,...,...,...,...,...,...,...
24486,"Red Butte CDP, Wyoming",Wyoming,Red Butte,False,False,False,True,WY,Red Butte WY,Red Butte,WY,42.8051,-106.4340
24487,"Chugcreek CDP, Wyoming",Wyoming,Chugcreek,False,False,False,True,WY,Chugcreek WY,Chugcreek,WY,42.0535,-104.9079
24488,"Wheatland town, Wyoming",Wyoming,Wheatland,False,True,False,False,WY,Wheatland WY,Wheatland,WY,42.0516,-104.9595
24489,"Boulder CDP, Wyoming",Wyoming,Boulder,False,False,False,True,WY,Boulder WY,Boulder,WY,42.7462,-109.7068
24490,"Dayton town, Wyoming",Wyoming,Dayton,False,True,False,False,WY,Dayton WY,Dayton,WY,44.8733,-107.2625
24491,"La Grange town, Wyoming",Wyoming,La Grange,False,True,False,False,WY,La Grange WY,La Grange,WY,41.6384,-104.1630
24492,"Alta CDP, Wyoming",Wyoming,Alta,False,False,False,True,WY,Alta WY,Alta,WY,43.7737,-111.0312
24493,"Jackson town, Wyoming",Wyoming,Jackson,False,True,False,False,WY,Jackson WY,Jackson,WY,43.4721,-110.7745
24494,"Teton Village CDP, Wyoming",Wyoming,Teton Village,False,False,False,True,WY,Teton Village WY,Teton Village,WY,43.5931,-110.8441
24495,"Cowley town, Wyoming",Wyoming,Cowley,False,True,False,False,WY,Cowley WY,Cowley,WY,44.8833,-108.4695
24496,"Hanna town, Wyoming",Wyoming,Hanna,False,True,False,False,WY,Hanna WY,Hanna,WY,41.8698,-106.5596
24497,"Sinclair town, Wyoming",Wyoming,Sinclair,False,True,False,False,WY,Sinclair WY,Sinclair,WY,41.7761,-107.1199
24498,"Warren AFB CDP, Wyoming",Wyoming,Warren AFB,False,False,False,True,WY,Warren AFB WY,Warren AFB,WY,41.1488,-104.8618
24499,"Lyman town, Wyoming",Wyoming,Lyman,False,True,False,False,WY,Lyman WY,Lyman,WY,41.3275,-110.2975
24500,"Thermopolis town, Wyoming",Wyoming,Thermopolis,False,True,False,False,WY,Thermopolis WY,Thermopolis,WY,43.6479,-108.2139
24501,"Boulder Flats CDP, Wyoming",Wyoming,Boulder Flats,False,False,False,True,WY,Boulder Flats WY,Boulder Flats,WY,42.9156,-108.7993
24502,"Shell CDP, Wyoming",Wyoming,Shell,False,False,False,True,WY,Shell WY,Shell,WY,44.5346,-107.7843
24503,"Kelly CDP, Wyoming",Wyoming,Kelly,False,False,False,True,WY,Kelly WY,Kelly,WY,43.6228,-110.6275
24504,"Whiting CDP, Wyoming",Wyoming,Whiting,False,False,False,True,WY,Whiting WY,Whiting,WY,42.0089,-104.9711
24505,"Orin CDP, Wyoming",Wyoming,Orin,False,False,False,True,WY,Orin WY,Orin,WY,42.6506,-105.1824
24506,"Carpenter CDP, Wyoming",Wyoming,Carpenter,False,False,False,True,WY,Carpenter WY,Carpenter,WY,41.0456,-104.3644
24507,"Hillsdale CDP, Wyoming",Wyoming,Hillsdale,False,False,False,True,WY,Hillsdale WY,Hillsdale,WY,41.2080,-104.4744
24508,"Beulah CDP, Wyoming",Wyoming,Beulah,False,False,False,True,WY,Beulah WY,Beulah,WY,44.5460,-104.0826
24509,"Mammoth CDP, Wyoming",Wyoming,Mammoth,False,False,False,True,WY,Mammoth WY,Mammoth,WY,44.9733,-110.6930
24510,"Osmond CDP, Wyoming",Wyoming,Osmond,False,False,False,True,WY,Osmond WY,Osmond,WY,42.6779,-110.9406
24511,"Nordic CDP, Wyoming",Wyoming,Nordic,False,False,False,True,WY,Nordic WY,Nordic,WY,43.0793,-110.9913
24512,"Freedom CDP, Wyoming",Wyoming,Freedom,False,False,False,True,WY,Freedom WY,Freedom,WY,42.9854,-111.0296
24513,"Urie CDP, Wyoming",Wyoming,Urie,False,False,False,True,WY,Urie WY,Urie,WY,41.3089,-110.3352
24514,"Ryan Park CDP, Wyoming",Wyoming,Ryan Park,False,False,False,True,WY,Ryan Park WY,Ryan Park,WY,41.3130,-106.4895
24515,"Arlington CDP, Wyoming",Wyoming,Arlington,False,False,False,True,WY,Arlington WY,Arlington,WY,41.6052,-106.1997

In [97]:
kentucky = df[df['State'] == "Kentucky"]

In [98]:
kentucky

,NAME,State,City,Place_Type_city,Place_Type_town,Place_Type_borough,Place_Type_CPD,State_Abbrev,City_ST,city,state_id,lat,lng
9777,"Evarts city, Kentucky",Kentucky,Evarts,True,False,False,False,KY,Evarts KY,Evarts,KY,36.8645,-83.1926
9778,"Loyall city, Kentucky",Kentucky,Loyall,True,False,False,False,KY,Loyall KY,Loyall,KY,36.8527,-83.3506
9779,"Lynch city, Kentucky",Kentucky,Lynch,True,False,False,False,KY,Lynch KY,Lynch,KY,36.9641,-82.9139
9780,"McKee city, Kentucky",Kentucky,McKee,True,False,False,False,KY,McKee KY,McKee,KY,37.4301,-83.9860
9781,"Blue Ridge Manor city, Kentucky",Kentucky,Blue Ridge Manor,True,False,False,False,KY,Blue Ridge Manor KY,Blue Ridge Manor,KY,38.2434,-85.5647
9782,"Cambridge city, Kentucky",Kentucky,Cambridge,True,False,False,False,KY,Cambridge KY,Cambridge,KY,38.2217,-85.6172
9783,"Bowling Green city, Kentucky",Kentucky,Bowling Green,True,False,False,False,KY,Bowling Green KY,Bowling Green,KY,36.9715,-86.4375
9784,"Glencoe city, Kentucky",Kentucky,Glencoe,True,False,False,False,KY,Glencoe KY,Glencoe,KY,38.7252,-84.8238
9785,"Monticello city, Kentucky",Kentucky,Monticello,True,False,False,False,KY,Monticello KY,Monticello,KY,36.8404,-84.8506
9786,"Versailles city, Kentucky",Kentucky,Versailles,True,False,False,False,KY,Versailles KY,Versailles,KY,38.0488,-84.7260
9787,"Jackson city, Kentucky",Kentucky,Jackson,True,False,False,False,KY,Jackson KY,Jackson,KY,37.5589,-83.3782
9788,"Masonville CDP, Kentucky",Kentucky,Masonville,False,False,False,True,KY,Masonville KY,Masonville,KY,37.6718,-87.0511
9789,"Crittenden city, Kentucky",Kentucky,Crittenden,True,False,False,False,KY,Crittenden KY,Crittenden,KY,38.7754,-84.6137
9790,"Hawesville city, Kentucky",Kentucky,Hawesville,True,False,False,False,KY,Hawesville KY,Hawesville,KY,37.8962,-86.7562
9791,"Sonora city, Kentucky",Kentucky,Sonora,True,False,False,False,KY,Sonora KY,Sonora,KY,37.5319,-85.8947
9792,"Westwood CDP, Kentucky",Kentucky,Westwood,False,False,False,True,KY,Westwood KY,Westwood,KY,38.2796,-85.5842
9793,"Westwood city, Kentucky",Kentucky,Westwood,True,False,False,False,KY,Westwood KY,Westwood,KY,38.2796,-85.5842
9794,"Jeffersontown city, Kentucky",Kentucky,Jefferson,True,False,False,False,KY,Jefferson KY,NaN,NaN,NaN,NaN
9795,"Milton city, Kentucky",Kentucky,Milton,True,False,False,False,KY,Milton KY,Milton,KY,38.7113,-85.3735
9796,"Plum Springs city, Kentucky",Kentucky,Plum Springs,True,False,False,False,KY,Plum Springs KY,Plum Springs,KY,37.0197,-86.3823
9797,"Wheelwright city, Kentucky",Kentucky,Wheelwright,True,False,False,False,KY,Wheelwright KY,Wheelwright,KY,37.3392,-82.7186
9798,"Wingo city, Kentucky",Kentucky,Wingo,True,False,False,False,KY,Wingo KY,Wingo,KY,36.6422,-88.7396
9799,"Greensburg city, Kentucky",Kentucky,Greensburg,True,False,False,False,KY,Greensburg KY,Greensburg,KY,37.2598,-85.4965
9800,"Benham city, Kentucky",Kentucky,Benham,True,False,False,False,KY,Benham KY,Benham,KY,36.9653,-82.9548
9801,"Rockholds CDP, Kentucky",Kentucky,Rockholds,False,False,False,True,KY,Rockholds KY,Rockholds,KY,36.8308,-84.1131
9802,"Virgie CDP, Kentucky",Kentucky,Virgie,False,False,False,True,KY,Virgie KY,Virgie,KY,37.3323,-82.5824
9803,"Freeburn CDP, Kentucky",Kentucky,Freeburn,False,False,False,True,KY,Freeburn KY,Freeburn,KY,37.5619,-82.1514
9804,"McCarr CDP, Kentucky",Kentucky,McCarr,False,False,False,True,KY,McCarr KY,McCarr,KY,37.6178,-82.1706
9805,"South Williamson CDP, Kentucky",Kentucky,South Williamson,False,False,False,True,KY,South Williamson KY,South Williamson,KY,37.6633,-82.2879
9806,"Crayne CDP, Kentucky",Kentucky,Crayne,False,False,False,True,KY,Crayne KY,Crayne,KY,37.2762,-88.0839
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10286,"Cawood CDP, Kentucky",Kentucky,Cawood,False,False,False,True,KY,Cawood KY,Cawood,KY,36.7878,-83.2284
10287,"Gilbertsville CDP, Kentucky",Kentucky,Gilbertsville,False,False,False,True,KY,Gilbertsville KY,Gilbertsville,KY,37.0284,-88.3104
10288,"Summersville CDP, Kentucky",Kentucky,Summersville,False,False,False,True,KY,Summersville KY,Summersville,KY,37.3265,-85.5430
10289,"Garrison CDP, Kentucky",Kentucky,Garrison,False,False,False,True,KY,Garrison KY,Garrison,KY,38.6075,-83.1834
10290,"Burna CDP, Kentucky",Kentucky,Burna,False,False,False,True,KY,Burna KY,Burna,KY,37.2456,-88.3589
10291,"Summer Shade CDP, Kentucky",Kentucky,Summer Shade,False,False,False,True,KY,Summer Shade KY,Summer Shade,KY,36.8837,-85.7098
10292,"Farmers CDP, Kentucky",Kentucky,Farmers,False,False,False,True,KY,Farmers KY,Farmers,KY,38.1405,-83.5414
10293,"Onton CDP, Kentucky",Kentucky,Onton,False,False,False,True,KY,Onton KY,Onton,KY,37.5579,-87.4371
10294,"Kenvir CDP, Kentucky",Kentucky,Kenvir,False,False,False,True,KY,Kenvir KY,Kenvir,KY,36.8531,-83.1539
10295,"Pathfork CDP, Kentucky",Kentucky,Pathfork,False,False,False,True,KY,Pathfork KY,Pathfork,KY,36.7594,-83.4711
10296,"Elk Creek CDP, Kentucky",Kentucky,Elk Creek,False,False,False,True,KY,Elk Creek KY,Elk Creek,KY,38.1170,-85.3722
10297,"Dunmor CDP, Kentucky",Kentucky,Dunmor,False,False,False,True,KY,Dunmor KY,Dunmor,KY,37.0753,-86.9951
10298,"Maytown CDP, Kentucky",Kentucky,May,False,False,False,True,KY,May KY,NaN,NaN,NaN,NaN
10299,"Cleaton CDP, Kentucky",Kentucky,Cleaton,False,False,False,True,KY,Cleaton KY,Cleaton,KY,37.2518,-87.0903
10300,"Utica CDP, Kentucky",Kentucky,Utica,False,False,False,True,KY,Utica KY,Utica,KY,37.6028,-87.1126
10301,"Kuttawa city, Kentucky",Kentucky,Kuttawa,True,False,False,False,KY,Kuttawa KY,Kuttawa,KY,37.0593,-88.1150
10302,"Brandenburg city, Kentucky",Kentucky,Brandenburg,True,False,False,False,KY,Brandenburg KY,Brandenburg,KY,37.9955,-86.1766
10303,"Clay city, Kentucky",Kentucky,Clay,True,False,False,False,KY,Clay KY,Clay,KY,37.4763,-87.8203
10304,"Wheatcroft city, Kentucky",Kentucky,Wheatcroft,True,False,False,False,KY,Wheatcroft KY,Wheatcroft,KY,37.4893,-87.8612
10305,"Augusta city, Kentucky",Kentucky,Augusta,True,False,False,False,KY,Augusta KY,Augusta,KY,38.7723,-84.0003
10306,"Pioneer Village city, Kentucky",Kentucky,Pioneer Village,True,False,False,False,KY,Pioneer Village KY,Pioneer Village,KY,38.0599,-85.6800
10307,"Newport city, Kentucky",Kentucky,Newport,True,False,False,False,KY,Newport KY,Newport,KY,39.0855,-84.4868
10308,"St. Regis Park city, Kentucky",Kentucky,St. Regis Park,True,False,False,False,KY,St. Regis Park KY,St. Regis Park,KY,38.2289,-85.6159
10309,"South Park View city, Kentucky",Kentucky,South Park View,True,False,False,False,KY,South Park View KY,South Park View,KY,38.1184,-85.7201
10310,"Spring Mill city, Kentucky",Kentucky,Spring Mill,True,False,False,False,KY,Spring Mill KY,Spring Mill,KY,38.1436,-85.6315
10311,"Strathmoor Village city, Kentucky",Kentucky,Strathmoor Village,True,False,False,False,KY,Strathmoor Village KY,Strathmoor Village,KY,38.2208,-85.6778
10312,"Sycamore city, Kentucky",Kentucky,Sycamore,True,False,False,False,KY,Sycamore KY,Sycamore,KY,38.2468,-85.5612
10313,"Water Valley city, Kentucky",Kentucky,Water Valley,True,False,False,False,KY,Water Valley KY,Water Valley,KY,36.5686,-88.8102
10314,"Flatwoods city, Kentucky",Kentucky,Flatwoods,True,False,False,False,KY,Flatwoods KY,Flatwoods,KY,38.5211,-82.7194
10315,"Russell city, Kentucky",Kentucky,Russell,True,False,False,False,KY,Russell KY,Russell,KY,38.5116,-82.6996

In [115]:
reduced.describe()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,ESTIMATESBASE2010,POPESTIMATE2010,POPESTIMATE2011,...,POPESTIMATE2016,POPESTIMATE2017,POPESTIMATE2018,county_fips,lat,lng,population,density,ranking,id
count,11435.000000,11435.000000,11435.000000,11435.000000,11435.000000,11435.000000,11435.000000,1.143500e+04,1.143500e+04,1.143500e+04,...,1.143500e+04,1.143500e+04,1.143500e+04,11435.000000,11435.000000,11435.000000,1.143500e+04,11435.000000,11435.000000,1.143500e+04
mean,132.630083,31.184609,91.121207,39159.947530,11581.227722,17.109488,0.909051,1.069612e+04,1.071796e+04,1.081237e+04,...,1.129253e+04,1.136900e+04,1.144083e+04,31281.741583,38.722532,-94.078242,1.974761e+04,496.756712,2.950765,1.840014e+09
std,39.760760,15.949383,89.887014,25057.923093,22597.605424,888.935481,0.287549,9.449621e+04,9.467263e+04,9.563490e+04,...,9.906229e+04,9.899679e+04,9.887505e+04,15960.971609,5.741854,13.127085,2.635689e+05,698.268243,0.226247,8.621181e+03
min,61.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,1001.000000,24.563700,-176.629500,0.000000e+00,0.000000,1.000000,1.840000e+09
25%,71.000000,19.000000,31.000000,17100.000000,0.000000,0.000000,1.000000,3.980000e+02,3.980000e+02,3.980000e+02,...,3.960000e+02,3.970000e+02,3.965000e+02,19061.000000,34.446100,-97.988450,3.880000e+02,155.000000,3.000000,1.840007e+09
50%,157.000000,29.000000,71.000000,39448.000000,0.000000,0.000000,1.000000,1.245000e+03,1.244000e+03,1.245000e+03,...,1.255000e+03,1.258000e+03,1.260000e+03,29205.000000,38.534800,-92.954300,1.267000e+03,328.000000,3.000000,1.840015e+09
75%,157.000000,47.000000,123.000000,60067.500000,8212.500000,0.000000,1.000000,5.260500e+03,5.274500e+03,5.281000e+03,...,5.372000e+03,5.422500e+03,5.464500e+03,47092.000000,42.880700,-85.431150,6.016000e+03,581.000000,3.000000,1.840020e+09
max,172.000000,56.000000,840.000000,89320.000000,89325.000000,52004.000000,1.000000,8.174988e+06,8.190355e+06,8.272963e+06,...,8.475976e+06,8.438271e+06,8.398748e+06,56045.000000,70.638000,-67.018300,1.935492e+07,23394.000000,3.000000,1.840142e+09

In [123]:
reduced = reduced.sort_values(by='POPESTIMATE2018', ascending=0)

In [124]:
reduced.head()

,SUMLEV,STATE,COUNTY,PLACE,COUSUB,CONCIT,PRIMGEO_FLAG,FUNCSTAT,NAME,STNAME,...,lng,population,density,source,military,incorporated,timezone,ranking,zips,id
21713,162,36,0,51000,0,0,0,A,New York city,New York,...,-73.9249,19354922.0,11083.0,polygon,False,True,America/New_York,1,11229 11226 11225 11224 11222 11221 11220 1138...,1840034016
2798,157,6,37,44000,0,0,1,A,Los Angeles city,California,...,-118.4068,12815475.0,3295.0,polygon,False,True,America/Los_Angeles,1,90291 90293 90292 91316 91311 90037 90031 9000...,1840020491
30378,162,48,0,35000,0,0,0,A,Houston city,Texas,...,-95.3905,5446468.0,1401.0,polygon,False,True,America/Chicago,1,77069 77068 77061 77060 77063 77062 77065 7706...,1840020925
31257,162,48,0,65000,0,0,0,A,San Antonio city,Texas,...,-98.5254,2002530.0,1204.0,polygon,False,True,America/Chicago,1,78112 78259 78258 78252 78251 78250 78257 7825...,1840022220
29965,162,48,0,19000,0,0,0,A,Dallas city,Texas,...,-96.7662,5733259.0,1524.0,polygon,False,True,America/Chicago,1,75287 75098 75233 75254 75251 75252 75253 7503...,1840019440

In [125]:
KS = reduced[reduced.STNAME == 'Kansas']

In [128]:
KS.columns

Index(['SUMLEV', 'STATE', 'COUNTY', 'PLACE', 'COUSUB', 'CONCIT',
       'PRIMGEO_FLAG', 'FUNCSTAT', 'NAME', 'STNAME', 'CENSUS2010POP',
       'ESTIMATESBASE2010', 'POPESTIMATE2010', 'POPESTIMATE2011',
       'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014',
       'POPESTIMATE2015', 'POPESTIMATE2016', 'POPESTIMATE2017',
       'POPESTIMATE2018', 'state_abbrev', 'city_x', 'city_state', 'city_y',
       'city_ascii', 'state_id', 'state_name', 'county_fips', 'county_name',
       'county_fips_all', 'county_name_all', 'lat', 'lng', 'population',
       'density', 'source', 'military', 'incorporated', 'timezone', 'ranking',
       'zips', 'id'],
      dtype='object')

In [104]:
uscities.shape

(28889, 20)